// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/firmware_management.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CleanupOldFirmwareRequest is the request to clean up old firmware files
type CleanupOldFirmwareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupOldFirmwareRequest) Reset() {
	*x = CleanupOldFirmwareRequest{}
	mi := &file_proto_firmware_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupOldFirmwareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupOldFirmwareRequest) ProtoMessage() {}

func (x *CleanupOldFirmwareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_firmware_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupOldFirmwareRequest.ProtoReflect.Descriptor instead.
func (*CleanupOldFirmwareRequest) Descriptor() ([]byte, []int) {
	return file_proto_firmware_management_proto_rawDescGZIP(), []int{0}
}

// CleanupOldFirmwareResponse contains the result of the cleanup operation
type CleanupOldFirmwareResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of files that were successfully deleted
	FilesDeleted int32 `protobuf:"varint,1,opt,name=files_deleted,json=filesDeleted,proto3" json:"files_deleted,omitempty"`
	// List of files that were deleted
	DeletedFiles []string `protobuf:"bytes,2,rep,name=deleted_files,json=deletedFiles,proto3" json:"deleted_files,omitempty"`
	// Any errors encountered during cleanup (non-fatal)
	Errors []string `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	// Total space freed in bytes
	SpaceFreedBytes int64 `protobuf:"varint,4,opt,name=space_freed_bytes,json=spaceFreedBytes,proto3" json:"space_freed_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CleanupOldFirmwareResponse) Reset() {
	*x = CleanupOldFirmwareResponse{}
	mi := &file_proto_firmware_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupOldFirmwareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupOldFirmwareResponse) ProtoMessage() {}

func (x *CleanupOldFirmwareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_firmware_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupOldFirmwareResponse.ProtoReflect.Descriptor instead.
func (*CleanupOldFirmwareResponse) Descriptor() ([]byte, []int) {
	return file_proto_firmware_management_proto_rawDescGZIP(), []int{1}
}

func (x *CleanupOldFirmwareResponse) GetFilesDeleted() int32 {
	if x != nil {
		return x.FilesDeleted
	}
	return 0
}

func (x *CleanupOldFirmwareResponse) GetDeletedFiles() []string {
	if x != nil {
		return x.DeletedFiles
	}
	return nil
}

func (x *CleanupOldFirmwareResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CleanupOldFirmwareResponse) GetSpaceFreedBytes() int64 {
	if x != nil {
		return x.SpaceFreedBytes
	}
	return 0
}

var File_proto_firmware_management_proto protoreflect.FileDescriptor

const file_proto_firmware_management_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/firmware_management.proto\x12\x05sonic\"\x1b\n" +
	"\x19CleanupOldFirmwareRequest\"\xaa\x01\n" +
	"\x1aCleanupOldFirmwareResponse\x12#\n" +
	"\rfiles_deleted\x18\x01 \x01(\x05R\ffilesDeleted\x12#\n" +
	"\rdeleted_files\x18\x02 \x03(\tR\fdeletedFiles\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12*\n" +
	"\x11space_freed_bytes\x18\x04 \x01(\x03R\x0fspaceFreedBytes2q\n" +
	"\x12FirmwareManagement\x12[\n" +
	"\x12CleanupOldFirmware\x12 .sonic.CleanupOldFirmwareRequest\x1a!.sonic.CleanupOldFirmwareResponse\"\x00B7Z5github.com/sonic-net/sonic-gnmi/upgrade-service/protob\x06proto3"

var (
	file_proto_firmware_management_proto_rawDescOnce sync.Once
	file_proto_firmware_management_proto_rawDescData []byte
)

func file_proto_firmware_management_proto_rawDescGZIP() []byte {
	file_proto_firmware_management_proto_rawDescOnce.Do(func() {
		file_proto_firmware_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_firmware_management_proto_rawDesc), len(file_proto_firmware_management_proto_rawDesc)))
	})
	return file_proto_firmware_management_proto_rawDescData
}

var file_proto_firmware_management_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_firmware_management_proto_goTypes = []any{
	(*CleanupOldFirmwareRequest)(nil),  // 0: sonic.CleanupOldFirmwareRequest
	(*CleanupOldFirmwareResponse)(nil), // 1: sonic.CleanupOldFirmwareResponse
}
var file_proto_firmware_management_proto_depIdxs = []int32{
	0, // 0: sonic.FirmwareManagement.CleanupOldFirmware:input_type -> sonic.CleanupOldFirmwareRequest
	1, // 1: sonic.FirmwareManagement.CleanupOldFirmware:output_type -> sonic.CleanupOldFirmwareResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_firmware_management_proto_init() }
func file_proto_firmware_management_proto_init() {
	if File_proto_firmware_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_firmware_management_proto_rawDesc), len(file_proto_firmware_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_firmware_management_proto_goTypes,
		DependencyIndexes: file_proto_firmware_management_proto_depIdxs,
		MessageInfos:      file_proto_firmware_management_proto_msgTypes,
	}.Build()
	File_proto_firmware_management_proto = out.File
	file_proto_firmware_management_proto_goTypes = nil
	file_proto_firmware_management_proto_depIdxs = nil
}
