// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/system_info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPlatformTypeRequest is an empty request to get the platform type
type GetPlatformTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformTypeRequest) Reset() {
	*x = GetPlatformTypeRequest{}
	mi := &file_proto_system_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformTypeRequest) ProtoMessage() {}

func (x *GetPlatformTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformTypeRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{0}
}

// GetPlatformTypeResponse contains the platform type information
type GetPlatformTypeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The primary string representation of the platform type (e.g., "mellanox_sn4600", "arista_7050")
	PlatformIdentifier string `protobuf:"bytes,1,opt,name=platform_identifier,json=platformIdentifier,proto3" json:"platform_identifier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPlatformTypeResponse) Reset() {
	*x = GetPlatformTypeResponse{}
	mi := &file_proto_system_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformTypeResponse) ProtoMessage() {}

func (x *GetPlatformTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformTypeResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlatformTypeResponse) GetPlatformIdentifier() string {
	if x != nil {
		return x.PlatformIdentifier
	}
	return ""
}

// GetDiskSpaceRequest is the request for disk space information
type GetDiskSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: specific paths to check (if empty, checks default paths)
	Paths         []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskSpaceRequest) Reset() {
	*x = GetDiskSpaceRequest{}
	mi := &file_proto_system_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskSpaceRequest) ProtoMessage() {}

func (x *GetDiskSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskSpaceRequest.ProtoReflect.Descriptor instead.
func (*GetDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{2}
}

func (x *GetDiskSpaceRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// GetDiskSpaceResponse contains disk space information for filesystems
type GetDiskSpaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Disk space information for each filesystem
	Filesystems   []*GetDiskSpaceResponse_DiskSpaceInfo `protobuf:"bytes,1,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskSpaceResponse) Reset() {
	*x = GetDiskSpaceResponse{}
	mi := &file_proto_system_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskSpaceResponse) ProtoMessage() {}

func (x *GetDiskSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskSpaceResponse.ProtoReflect.Descriptor instead.
func (*GetDiskSpaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiskSpaceResponse) GetFilesystems() []*GetDiskSpaceResponse_DiskSpaceInfo {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

// DiskSpaceInfo contains space information for a single filesystem
type GetDiskSpaceResponse_DiskSpaceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of the filesystem (e.g., "/", "/host", "/tmp")
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Total space in megabytes
	TotalMb int64 `protobuf:"varint,2,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	// Free space in megabytes
	FreeMb int64 `protobuf:"varint,3,opt,name=free_mb,json=freeMb,proto3" json:"free_mb,omitempty"`
	// Used space in megabytes
	UsedMb int64 `protobuf:"varint,4,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	// Error message if this filesystem check failed
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) Reset() {
	*x = GetDiskSpaceResponse_DiskSpaceInfo{}
	mi := &file_proto_system_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskSpaceResponse_DiskSpaceInfo) ProtoMessage() {}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskSpaceResponse_DiskSpaceInfo.ProtoReflect.Descriptor instead.
func (*GetDiskSpaceResponse_DiskSpaceInfo) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetTotalMb() int64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetFreeMb() int64 {
	if x != nil {
		return x.FreeMb
	}
	return 0
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetUsedMb() int64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_system_info_proto protoreflect.FileDescriptor

const file_proto_system_info_proto_rawDesc = "" +
	"\n" +
	"\x17proto/system_info.proto\x12\x05sonic\"\x18\n" +
	"\x16GetPlatformTypeRequest\"J\n" +
	"\x17GetPlatformTypeResponse\x12/\n" +
	"\x13platform_identifier\x18\x01 \x01(\tR\x12platformIdentifier\"+\n" +
	"\x13GetDiskSpaceRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"\xfb\x01\n" +
	"\x14GetDiskSpaceResponse\x12K\n" +
	"\vfilesystems\x18\x01 \x03(\v2).sonic.GetDiskSpaceResponse.DiskSpaceInfoR\vfilesystems\x1a\x95\x01\n" +
	"\rDiskSpaceInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\btotal_mb\x18\x02 \x01(\x03R\atotalMb\x12\x17\n" +
	"\afree_mb\x18\x03 \x01(\x03R\x06freeMb\x12\x17\n" +
	"\aused_mb\x18\x04 \x01(\x03R\x06usedMb\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage2\xab\x01\n" +
	"\n" +
	"SystemInfo\x12R\n" +
	"\x0fGetPlatformType\x12\x1d.sonic.GetPlatformTypeRequest\x1a\x1e.sonic.GetPlatformTypeResponse\"\x00\x12I\n" +
	"\fGetDiskSpace\x12\x1a.sonic.GetDiskSpaceRequest\x1a\x1b.sonic.GetDiskSpaceResponse\"\x00B7Z5github.com/sonic-net/sonic-gnmi/upgrade-service/protob\x06proto3"

var (
	file_proto_system_info_proto_rawDescOnce sync.Once
	file_proto_system_info_proto_rawDescData []byte
)

func file_proto_system_info_proto_rawDescGZIP() []byte {
	file_proto_system_info_proto_rawDescOnce.Do(func() {
		file_proto_system_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_info_proto_rawDesc), len(file_proto_system_info_proto_rawDesc)))
	})
	return file_proto_system_info_proto_rawDescData
}

var file_proto_system_info_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_system_info_proto_goTypes = []any{
	(*GetPlatformTypeRequest)(nil),             // 0: sonic.GetPlatformTypeRequest
	(*GetPlatformTypeResponse)(nil),            // 1: sonic.GetPlatformTypeResponse
	(*GetDiskSpaceRequest)(nil),                // 2: sonic.GetDiskSpaceRequest
	(*GetDiskSpaceResponse)(nil),               // 3: sonic.GetDiskSpaceResponse
	(*GetDiskSpaceResponse_DiskSpaceInfo)(nil), // 4: sonic.GetDiskSpaceResponse.DiskSpaceInfo
}
var file_proto_system_info_proto_depIdxs = []int32{
	4, // 0: sonic.GetDiskSpaceResponse.filesystems:type_name -> sonic.GetDiskSpaceResponse.DiskSpaceInfo
	0, // 1: sonic.SystemInfo.GetPlatformType:input_type -> sonic.GetPlatformTypeRequest
	2, // 2: sonic.SystemInfo.GetDiskSpace:input_type -> sonic.GetDiskSpaceRequest
	1, // 3: sonic.SystemInfo.GetPlatformType:output_type -> sonic.GetPlatformTypeResponse
	3, // 4: sonic.SystemInfo.GetDiskSpace:output_type -> sonic.GetDiskSpaceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_system_info_proto_init() }
func file_proto_system_info_proto_init() {
	if File_proto_system_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_info_proto_rawDesc), len(file_proto_system_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_info_proto_goTypes,
		DependencyIndexes: file_proto_system_info_proto_depIdxs,
		MessageInfos:      file_proto_system_info_proto_msgTypes,
	}.Build()
	File_proto_system_info_proto = out.File
	file_proto_system_info_proto_goTypes = nil
	file_proto_system_info_proto_depIdxs = nil
}
