// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/system_info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShowCommandType enumerates the supported show command types
type ShowCommandType int32

const (
	ShowCommandType_SHOW_COMMAND_TYPE_UNSPECIFIED                     ShowCommandType = 0
	ShowCommandType_SHOW_COMMAND_TYPE_CHASSIS_MODULES_MIDPLANE_STATUS ShowCommandType = 1
	ShowCommandType_SHOW_COMMAND_TYPE_CHASSIS_MODULES_STATUS          ShowCommandType = 2
	ShowCommandType_SHOW_COMMAND_TYPE_SYSTEM_HEALTH_DPU               ShowCommandType = 3
)

// Enum value maps for ShowCommandType.
var (
	ShowCommandType_name = map[int32]string{
		0: "SHOW_COMMAND_TYPE_UNSPECIFIED",
		1: "SHOW_COMMAND_TYPE_CHASSIS_MODULES_MIDPLANE_STATUS",
		2: "SHOW_COMMAND_TYPE_CHASSIS_MODULES_STATUS",
		3: "SHOW_COMMAND_TYPE_SYSTEM_HEALTH_DPU",
	}
	ShowCommandType_value = map[string]int32{
		"SHOW_COMMAND_TYPE_UNSPECIFIED":                     0,
		"SHOW_COMMAND_TYPE_CHASSIS_MODULES_MIDPLANE_STATUS": 1,
		"SHOW_COMMAND_TYPE_CHASSIS_MODULES_STATUS":          2,
		"SHOW_COMMAND_TYPE_SYSTEM_HEALTH_DPU":               3,
	}
)

func (x ShowCommandType) Enum() *ShowCommandType {
	p := new(ShowCommandType)
	*p = x
	return p
}

func (x ShowCommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShowCommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_system_info_proto_enumTypes[0].Descriptor()
}

func (ShowCommandType) Type() protoreflect.EnumType {
	return &file_proto_system_info_proto_enumTypes[0]
}

func (x ShowCommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShowCommandType.Descriptor instead.
func (ShowCommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{0}
}

// GetPlatformTypeRequest is an empty request to get the platform type
type GetPlatformTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformTypeRequest) Reset() {
	*x = GetPlatformTypeRequest{}
	mi := &file_proto_system_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformTypeRequest) ProtoMessage() {}

func (x *GetPlatformTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformTypeRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{0}
}

// GetPlatformTypeResponse contains the platform type information
type GetPlatformTypeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The primary string representation of the platform type (e.g., "mellanox_sn4600", "arista_7050")
	PlatformIdentifier string `protobuf:"bytes,1,opt,name=platform_identifier,json=platformIdentifier,proto3" json:"platform_identifier,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetPlatformTypeResponse) Reset() {
	*x = GetPlatformTypeResponse{}
	mi := &file_proto_system_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformTypeResponse) ProtoMessage() {}

func (x *GetPlatformTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformTypeResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlatformTypeResponse) GetPlatformIdentifier() string {
	if x != nil {
		return x.PlatformIdentifier
	}
	return ""
}

// GetDiskSpaceRequest is the request for disk space information
type GetDiskSpaceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: specific paths to check (if empty, checks default paths)
	Paths         []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskSpaceRequest) Reset() {
	*x = GetDiskSpaceRequest{}
	mi := &file_proto_system_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskSpaceRequest) ProtoMessage() {}

func (x *GetDiskSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskSpaceRequest.ProtoReflect.Descriptor instead.
func (*GetDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{2}
}

func (x *GetDiskSpaceRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

// GetDiskSpaceResponse contains disk space information for filesystems
type GetDiskSpaceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Disk space information for each filesystem
	Filesystems   []*GetDiskSpaceResponse_DiskSpaceInfo `protobuf:"bytes,1,rep,name=filesystems,proto3" json:"filesystems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskSpaceResponse) Reset() {
	*x = GetDiskSpaceResponse{}
	mi := &file_proto_system_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskSpaceResponse) ProtoMessage() {}

func (x *GetDiskSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskSpaceResponse.ProtoReflect.Descriptor instead.
func (*GetDiskSpaceResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiskSpaceResponse) GetFilesystems() []*GetDiskSpaceResponse_DiskSpaceInfo {
	if x != nil {
		return x.Filesystems
	}
	return nil
}

// GetShowCommandRequest is the request for show command execution
type GetShowCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of show command to execute
	CommandType ShowCommandType `protobuf:"varint,1,opt,name=command_type,json=commandType,proto3,enum=sonic.ShowCommandType" json:"command_type,omitempty"`
	// Optional target (e.g., DPU name for specific DPU)
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Optional additional parameters as key-value pairs
	Parameters    map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowCommandRequest) Reset() {
	*x = GetShowCommandRequest{}
	mi := &file_proto_system_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowCommandRequest) ProtoMessage() {}

func (x *GetShowCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowCommandRequest.ProtoReflect.Descriptor instead.
func (*GetShowCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{4}
}

func (x *GetShowCommandRequest) GetCommandType() ShowCommandType {
	if x != nil {
		return x.CommandType
	}
	return ShowCommandType_SHOW_COMMAND_TYPE_UNSPECIFIED
}

func (x *GetShowCommandRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetShowCommandRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// DPUInfo contains information about a single DPU (for chassis commands)
type DPUInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the DPU (e.g., "DPU0", "DPU3")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// IP address of the DPU
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// Reachability status as string ("True", "False")
	Reachability string `protobuf:"bytes,3,opt,name=reachability,proto3" json:"reachability,omitempty"`
	// Reachability status as boolean
	Reachable     bool `protobuf:"varint,4,opt,name=reachable,proto3" json:"reachable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DPUInfo) Reset() {
	*x = DPUInfo{}
	mi := &file_proto_system_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPUInfo) ProtoMessage() {}

func (x *DPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPUInfo.ProtoReflect.Descriptor instead.
func (*DPUInfo) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{5}
}

func (x *DPUInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DPUInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *DPUInfo) GetReachability() string {
	if x != nil {
		return x.Reachability
	}
	return ""
}

func (x *DPUInfo) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

// DPUModuleInfo contains module status information for a DPU
type DPUModuleInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the DPU (e.g., "DPU0", "DPU3")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the module
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Physical slot information
	PhysicalSlot string `protobuf:"bytes,3,opt,name=physical_slot,json=physicalSlot,proto3" json:"physical_slot,omitempty"`
	// Operational status
	OperStatus string `protobuf:"bytes,4,opt,name=oper_status,json=operStatus,proto3" json:"oper_status,omitempty"`
	// Administrative status
	AdminStatus string `protobuf:"bytes,5,opt,name=admin_status,json=adminStatus,proto3" json:"admin_status,omitempty"`
	// Serial number
	Serial        string `protobuf:"bytes,6,opt,name=serial,proto3" json:"serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DPUModuleInfo) Reset() {
	*x = DPUModuleInfo{}
	mi := &file_proto_system_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DPUModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPUModuleInfo) ProtoMessage() {}

func (x *DPUModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPUModuleInfo.ProtoReflect.Descriptor instead.
func (*DPUModuleInfo) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{6}
}

func (x *DPUModuleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DPUModuleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DPUModuleInfo) GetPhysicalSlot() string {
	if x != nil {
		return x.PhysicalSlot
	}
	return ""
}

func (x *DPUModuleInfo) GetOperStatus() string {
	if x != nil {
		return x.OperStatus
	}
	return ""
}

func (x *DPUModuleInfo) GetAdminStatus() string {
	if x != nil {
		return x.AdminStatus
	}
	return ""
}

func (x *DPUModuleInfo) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

// SystemHealthDPUInfo contains system health information for a DPU
type SystemHealthDPUInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the DPU
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Operational status
	OperStatus string `protobuf:"bytes,2,opt,name=oper_status,json=operStatus,proto3" json:"oper_status,omitempty"`
	// List of state details
	StateDetails  []*StateDetail `protobuf:"bytes,3,rep,name=state_details,json=stateDetails,proto3" json:"state_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemHealthDPUInfo) Reset() {
	*x = SystemHealthDPUInfo{}
	mi := &file_proto_system_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemHealthDPUInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemHealthDPUInfo) ProtoMessage() {}

func (x *SystemHealthDPUInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemHealthDPUInfo.ProtoReflect.Descriptor instead.
func (*SystemHealthDPUInfo) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{7}
}

func (x *SystemHealthDPUInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SystemHealthDPUInfo) GetOperStatus() string {
	if x != nil {
		return x.OperStatus
	}
	return ""
}

func (x *SystemHealthDPUInfo) GetStateDetails() []*StateDetail {
	if x != nil {
		return x.StateDetails
	}
	return nil
}

// StateDetail represents a single state detail entry
type StateDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State detail name (e.g., "dpu_midplane_link_state")
	StateName string `protobuf:"bytes,1,opt,name=state_name,json=stateName,proto3" json:"state_name,omitempty"`
	// State value (e.g., "up", "down")
	StateValue string `protobuf:"bytes,2,opt,name=state_value,json=stateValue,proto3" json:"state_value,omitempty"`
	// Timestamp when this state was recorded
	Time string `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	// Optional reason for the state
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateDetail) Reset() {
	*x = StateDetail{}
	mi := &file_proto_system_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateDetail) ProtoMessage() {}

func (x *StateDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateDetail.ProtoReflect.Descriptor instead.
func (*StateDetail) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{8}
}

func (x *StateDetail) GetStateName() string {
	if x != nil {
		return x.StateName
	}
	return ""
}

func (x *StateDetail) GetStateValue() string {
	if x != nil {
		return x.StateValue
	}
	return ""
}

func (x *StateDetail) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *StateDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GetShowCommandResponse contains the response for show command execution
type GetShowCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command type that was executed
	CommandType ShowCommandType `protobuf:"varint,1,opt,name=command_type,json=commandType,proto3,enum=sonic.ShowCommandType" json:"command_type,omitempty"`
	// Target that was queried
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Whether an error occurred during command execution
	HasError bool `protobuf:"varint,3,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	// Any error message if the command failed
	ErrorMessage string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Raw command output for debugging (optional)
	RawOutput string `protobuf:"bytes,5,opt,name=raw_output,json=rawOutput,proto3" json:"raw_output,omitempty"`
	// Structured output based on command type
	//
	// Types that are valid to be assigned to Output:
	//
	//	*GetShowCommandResponse_ChassisModules
	//	*GetShowCommandResponse_ChassisModulesStatus
	//	*GetShowCommandResponse_SystemHealthDpu
	Output        isGetShowCommandResponse_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShowCommandResponse) Reset() {
	*x = GetShowCommandResponse{}
	mi := &file_proto_system_info_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShowCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShowCommandResponse) ProtoMessage() {}

func (x *GetShowCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShowCommandResponse.ProtoReflect.Descriptor instead.
func (*GetShowCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{9}
}

func (x *GetShowCommandResponse) GetCommandType() ShowCommandType {
	if x != nil {
		return x.CommandType
	}
	return ShowCommandType_SHOW_COMMAND_TYPE_UNSPECIFIED
}

func (x *GetShowCommandResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *GetShowCommandResponse) GetHasError() bool {
	if x != nil {
		return x.HasError
	}
	return false
}

func (x *GetShowCommandResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetShowCommandResponse) GetRawOutput() string {
	if x != nil {
		return x.RawOutput
	}
	return ""
}

func (x *GetShowCommandResponse) GetOutput() isGetShowCommandResponse_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *GetShowCommandResponse) GetChassisModules() *ChassisModulesOutput {
	if x != nil {
		if x, ok := x.Output.(*GetShowCommandResponse_ChassisModules); ok {
			return x.ChassisModules
		}
	}
	return nil
}

func (x *GetShowCommandResponse) GetChassisModulesStatus() *ChassisModulesStatusOutput {
	if x != nil {
		if x, ok := x.Output.(*GetShowCommandResponse_ChassisModulesStatus); ok {
			return x.ChassisModulesStatus
		}
	}
	return nil
}

func (x *GetShowCommandResponse) GetSystemHealthDpu() *SystemHealthDPUOutput {
	if x != nil {
		if x, ok := x.Output.(*GetShowCommandResponse_SystemHealthDpu); ok {
			return x.SystemHealthDpu
		}
	}
	return nil
}

type isGetShowCommandResponse_Output interface {
	isGetShowCommandResponse_Output()
}

type GetShowCommandResponse_ChassisModules struct {
	ChassisModules *ChassisModulesOutput `protobuf:"bytes,10,opt,name=chassis_modules,json=chassisModules,proto3,oneof"`
}

type GetShowCommandResponse_ChassisModulesStatus struct {
	ChassisModulesStatus *ChassisModulesStatusOutput `protobuf:"bytes,11,opt,name=chassis_modules_status,json=chassisModulesStatus,proto3,oneof"`
}

type GetShowCommandResponse_SystemHealthDpu struct {
	SystemHealthDpu *SystemHealthDPUOutput `protobuf:"bytes,12,opt,name=system_health_dpu,json=systemHealthDpu,proto3,oneof"`
}

func (*GetShowCommandResponse_ChassisModules) isGetShowCommandResponse_Output() {}

func (*GetShowCommandResponse_ChassisModulesStatus) isGetShowCommandResponse_Output() {}

func (*GetShowCommandResponse_SystemHealthDpu) isGetShowCommandResponse_Output() {}

// ChassisModulesOutput contains DPU chassis module information
type ChassisModulesOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dpus          []*DPUInfo             `protobuf:"bytes,1,rep,name=dpus,proto3" json:"dpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChassisModulesOutput) Reset() {
	*x = ChassisModulesOutput{}
	mi := &file_proto_system_info_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChassisModulesOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChassisModulesOutput) ProtoMessage() {}

func (x *ChassisModulesOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChassisModulesOutput.ProtoReflect.Descriptor instead.
func (*ChassisModulesOutput) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{10}
}

func (x *ChassisModulesOutput) GetDpus() []*DPUInfo {
	if x != nil {
		return x.Dpus
	}
	return nil
}

// ChassisModulesStatusOutput contains DPU module status information
type ChassisModulesStatusOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Modules       []*DPUModuleInfo       `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChassisModulesStatusOutput) Reset() {
	*x = ChassisModulesStatusOutput{}
	mi := &file_proto_system_info_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChassisModulesStatusOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChassisModulesStatusOutput) ProtoMessage() {}

func (x *ChassisModulesStatusOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChassisModulesStatusOutput.ProtoReflect.Descriptor instead.
func (*ChassisModulesStatusOutput) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{11}
}

func (x *ChassisModulesStatusOutput) GetModules() []*DPUModuleInfo {
	if x != nil {
		return x.Modules
	}
	return nil
}

// SystemHealthDPUOutput contains system health DPU information
type SystemHealthDPUOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dpus          []*SystemHealthDPUInfo `protobuf:"bytes,1,rep,name=dpus,proto3" json:"dpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemHealthDPUOutput) Reset() {
	*x = SystemHealthDPUOutput{}
	mi := &file_proto_system_info_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemHealthDPUOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemHealthDPUOutput) ProtoMessage() {}

func (x *SystemHealthDPUOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemHealthDPUOutput.ProtoReflect.Descriptor instead.
func (*SystemHealthDPUOutput) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{12}
}

func (x *SystemHealthDPUOutput) GetDpus() []*SystemHealthDPUInfo {
	if x != nil {
		return x.Dpus
	}
	return nil
}

// DiskSpaceInfo contains space information for a single filesystem
type GetDiskSpaceResponse_DiskSpaceInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of the filesystem (e.g., "/", "/host", "/tmp")
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Total space in megabytes
	TotalMb int64 `protobuf:"varint,2,opt,name=total_mb,json=totalMb,proto3" json:"total_mb,omitempty"`
	// Free space in megabytes
	FreeMb int64 `protobuf:"varint,3,opt,name=free_mb,json=freeMb,proto3" json:"free_mb,omitempty"`
	// Used space in megabytes
	UsedMb int64 `protobuf:"varint,4,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	// Error message if this filesystem check failed
	ErrorMessage  string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) Reset() {
	*x = GetDiskSpaceResponse_DiskSpaceInfo{}
	mi := &file_proto_system_info_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiskSpaceResponse_DiskSpaceInfo) ProtoMessage() {}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiskSpaceResponse_DiskSpaceInfo.ProtoReflect.Descriptor instead.
func (*GetDiskSpaceResponse_DiskSpaceInfo) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetTotalMb() int64 {
	if x != nil {
		return x.TotalMb
	}
	return 0
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetFreeMb() int64 {
	if x != nil {
		return x.FreeMb
	}
	return 0
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetUsedMb() int64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *GetDiskSpaceResponse_DiskSpaceInfo) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_system_info_proto protoreflect.FileDescriptor

const file_proto_system_info_proto_rawDesc = "" +
	"\n" +
	"\x17proto/system_info.proto\x12\x05sonic\"\x18\n" +
	"\x16GetPlatformTypeRequest\"J\n" +
	"\x17GetPlatformTypeResponse\x12/\n" +
	"\x13platform_identifier\x18\x01 \x01(\tR\x12platformIdentifier\"+\n" +
	"\x13GetDiskSpaceRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"\xfb\x01\n" +
	"\x14GetDiskSpaceResponse\x12K\n" +
	"\vfilesystems\x18\x01 \x03(\v2).sonic.GetDiskSpaceResponse.DiskSpaceInfoR\vfilesystems\x1a\x95\x01\n" +
	"\rDiskSpaceInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\btotal_mb\x18\x02 \x01(\x03R\atotalMb\x12\x17\n" +
	"\afree_mb\x18\x03 \x01(\x03R\x06freeMb\x12\x17\n" +
	"\aused_mb\x18\x04 \x01(\x03R\x06usedMb\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xf7\x01\n" +
	"\x15GetShowCommandRequest\x129\n" +
	"\fcommand_type\x18\x01 \x01(\x0e2\x16.sonic.ShowCommandTypeR\vcommandType\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12L\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2,.sonic.GetShowCommandRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\aDPUInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\"\n" +
	"\freachability\x18\x03 \x01(\tR\freachability\x12\x1c\n" +
	"\treachable\x18\x04 \x01(\bR\treachable\"\xc6\x01\n" +
	"\rDPUModuleInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rphysical_slot\x18\x03 \x01(\tR\fphysicalSlot\x12\x1f\n" +
	"\voper_status\x18\x04 \x01(\tR\n" +
	"operStatus\x12!\n" +
	"\fadmin_status\x18\x05 \x01(\tR\vadminStatus\x12\x16\n" +
	"\x06serial\x18\x06 \x01(\tR\x06serial\"\x83\x01\n" +
	"\x13SystemHealthDPUInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\voper_status\x18\x02 \x01(\tR\n" +
	"operStatus\x127\n" +
	"\rstate_details\x18\x03 \x03(\v2\x12.sonic.StateDetailR\fstateDetails\"y\n" +
	"\vStateDetail\x12\x1d\n" +
	"\n" +
	"state_name\x18\x01 \x01(\tR\tstateName\x12\x1f\n" +
	"\vstate_value\x18\x02 \x01(\tR\n" +
	"stateValue\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xc5\x03\n" +
	"\x16GetShowCommandResponse\x129\n" +
	"\fcommand_type\x18\x01 \x01(\x0e2\x16.sonic.ShowCommandTypeR\vcommandType\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1b\n" +
	"\thas_error\x18\x03 \x01(\bR\bhasError\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"raw_output\x18\x05 \x01(\tR\trawOutput\x12F\n" +
	"\x0fchassis_modules\x18\n" +
	" \x01(\v2\x1b.sonic.ChassisModulesOutputH\x00R\x0echassisModules\x12Y\n" +
	"\x16chassis_modules_status\x18\v \x01(\v2!.sonic.ChassisModulesStatusOutputH\x00R\x14chassisModulesStatus\x12J\n" +
	"\x11system_health_dpu\x18\f \x01(\v2\x1c.sonic.SystemHealthDPUOutputH\x00R\x0fsystemHealthDpuB\b\n" +
	"\x06output\":\n" +
	"\x14ChassisModulesOutput\x12\"\n" +
	"\x04dpus\x18\x01 \x03(\v2\x0e.sonic.DPUInfoR\x04dpus\"L\n" +
	"\x1aChassisModulesStatusOutput\x12.\n" +
	"\amodules\x18\x01 \x03(\v2\x14.sonic.DPUModuleInfoR\amodules\"G\n" +
	"\x15SystemHealthDPUOutput\x12.\n" +
	"\x04dpus\x18\x01 \x03(\v2\x1a.sonic.SystemHealthDPUInfoR\x04dpus*\xc2\x01\n" +
	"\x0fShowCommandType\x12!\n" +
	"\x1dSHOW_COMMAND_TYPE_UNSPECIFIED\x10\x00\x125\n" +
	"1SHOW_COMMAND_TYPE_CHASSIS_MODULES_MIDPLANE_STATUS\x10\x01\x12,\n" +
	"(SHOW_COMMAND_TYPE_CHASSIS_MODULES_STATUS\x10\x02\x12'\n" +
	"#SHOW_COMMAND_TYPE_SYSTEM_HEALTH_DPU\x10\x032\x82\x02\n" +
	"\n" +
	"SystemInfo\x12R\n" +
	"\x0fGetPlatformType\x12\x1d.sonic.GetPlatformTypeRequest\x1a\x1e.sonic.GetPlatformTypeResponse\"\x00\x12I\n" +
	"\fGetDiskSpace\x12\x1a.sonic.GetDiskSpaceRequest\x1a\x1b.sonic.GetDiskSpaceResponse\"\x00\x12U\n" +
	"\x14GetShowCommandOutput\x12\x1c.sonic.GetShowCommandRequest\x1a\x1d.sonic.GetShowCommandResponse\"\x00B7Z5github.com/sonic-net/sonic-gnmi/upgrade-service/protob\x06proto3"

var (
	file_proto_system_info_proto_rawDescOnce sync.Once
	file_proto_system_info_proto_rawDescData []byte
)

func file_proto_system_info_proto_rawDescGZIP() []byte {
	file_proto_system_info_proto_rawDescOnce.Do(func() {
		file_proto_system_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_info_proto_rawDesc), len(file_proto_system_info_proto_rawDesc)))
	})
	return file_proto_system_info_proto_rawDescData
}

var file_proto_system_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_system_info_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_system_info_proto_goTypes = []any{
	(ShowCommandType)(0),                       // 0: sonic.ShowCommandType
	(*GetPlatformTypeRequest)(nil),             // 1: sonic.GetPlatformTypeRequest
	(*GetPlatformTypeResponse)(nil),            // 2: sonic.GetPlatformTypeResponse
	(*GetDiskSpaceRequest)(nil),                // 3: sonic.GetDiskSpaceRequest
	(*GetDiskSpaceResponse)(nil),               // 4: sonic.GetDiskSpaceResponse
	(*GetShowCommandRequest)(nil),              // 5: sonic.GetShowCommandRequest
	(*DPUInfo)(nil),                            // 6: sonic.DPUInfo
	(*DPUModuleInfo)(nil),                      // 7: sonic.DPUModuleInfo
	(*SystemHealthDPUInfo)(nil),                // 8: sonic.SystemHealthDPUInfo
	(*StateDetail)(nil),                        // 9: sonic.StateDetail
	(*GetShowCommandResponse)(nil),             // 10: sonic.GetShowCommandResponse
	(*ChassisModulesOutput)(nil),               // 11: sonic.ChassisModulesOutput
	(*ChassisModulesStatusOutput)(nil),         // 12: sonic.ChassisModulesStatusOutput
	(*SystemHealthDPUOutput)(nil),              // 13: sonic.SystemHealthDPUOutput
	(*GetDiskSpaceResponse_DiskSpaceInfo)(nil), // 14: sonic.GetDiskSpaceResponse.DiskSpaceInfo
	nil, // 15: sonic.GetShowCommandRequest.ParametersEntry
}
var file_proto_system_info_proto_depIdxs = []int32{
	14, // 0: sonic.GetDiskSpaceResponse.filesystems:type_name -> sonic.GetDiskSpaceResponse.DiskSpaceInfo
	0,  // 1: sonic.GetShowCommandRequest.command_type:type_name -> sonic.ShowCommandType
	15, // 2: sonic.GetShowCommandRequest.parameters:type_name -> sonic.GetShowCommandRequest.ParametersEntry
	9,  // 3: sonic.SystemHealthDPUInfo.state_details:type_name -> sonic.StateDetail
	0,  // 4: sonic.GetShowCommandResponse.command_type:type_name -> sonic.ShowCommandType
	11, // 5: sonic.GetShowCommandResponse.chassis_modules:type_name -> sonic.ChassisModulesOutput
	12, // 6: sonic.GetShowCommandResponse.chassis_modules_status:type_name -> sonic.ChassisModulesStatusOutput
	13, // 7: sonic.GetShowCommandResponse.system_health_dpu:type_name -> sonic.SystemHealthDPUOutput
	6,  // 8: sonic.ChassisModulesOutput.dpus:type_name -> sonic.DPUInfo
	7,  // 9: sonic.ChassisModulesStatusOutput.modules:type_name -> sonic.DPUModuleInfo
	8,  // 10: sonic.SystemHealthDPUOutput.dpus:type_name -> sonic.SystemHealthDPUInfo
	1,  // 11: sonic.SystemInfo.GetPlatformType:input_type -> sonic.GetPlatformTypeRequest
	3,  // 12: sonic.SystemInfo.GetDiskSpace:input_type -> sonic.GetDiskSpaceRequest
	5,  // 13: sonic.SystemInfo.GetShowCommandOutput:input_type -> sonic.GetShowCommandRequest
	2,  // 14: sonic.SystemInfo.GetPlatformType:output_type -> sonic.GetPlatformTypeResponse
	4,  // 15: sonic.SystemInfo.GetDiskSpace:output_type -> sonic.GetDiskSpaceResponse
	10, // 16: sonic.SystemInfo.GetShowCommandOutput:output_type -> sonic.GetShowCommandResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_system_info_proto_init() }
func file_proto_system_info_proto_init() {
	if File_proto_system_info_proto != nil {
		return
	}
	file_proto_system_info_proto_msgTypes[9].OneofWrappers = []any{
		(*GetShowCommandResponse_ChassisModules)(nil),
		(*GetShowCommandResponse_ChassisModulesStatus)(nil),
		(*GetShowCommandResponse_SystemHealthDpu)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_info_proto_rawDesc), len(file_proto_system_info_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_info_proto_goTypes,
		DependencyIndexes: file_proto_system_info_proto_depIdxs,
		EnumInfos:         file_proto_system_info_proto_enumTypes,
		MessageInfos:      file_proto_system_info_proto_msgTypes,
	}.Build()
	File_proto_system_info_proto = out.File
	file_proto_system_info_proto_goTypes = nil
	file_proto_system_info_proto_depIdxs = nil
}
