// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/system_info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPlatformTypeRequest is an empty request to get the platform type
type GetPlatformTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformTypeRequest) Reset() {
	*x = GetPlatformTypeRequest{}
	mi := &file_proto_system_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformTypeRequest) ProtoMessage() {}

func (x *GetPlatformTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformTypeRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{0}
}

// GetPlatformTypeResponse contains the platform type information
type GetPlatformTypeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The primary string representation of the platform type (e.g., "mellanox_sn4600", "arista_7050")
	PlatformIdentifier string `protobuf:"bytes,1,opt,name=platform_identifier,json=platformIdentifier,proto3" json:"platform_identifier,omitempty"`
	// Vendor of the platform (e.g., "mellanox", "arista", "cisco")
	Vendor string `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	// Model of the platform (e.g., "sn4600", "7050")
	Model         string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformTypeResponse) Reset() {
	*x = GetPlatformTypeResponse{}
	mi := &file_proto_system_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformTypeResponse) ProtoMessage() {}

func (x *GetPlatformTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_system_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformTypeResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_system_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlatformTypeResponse) GetPlatformIdentifier() string {
	if x != nil {
		return x.PlatformIdentifier
	}
	return ""
}

func (x *GetPlatformTypeResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GetPlatformTypeResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_proto_system_info_proto protoreflect.FileDescriptor

const file_proto_system_info_proto_rawDesc = "" +
	"\n" +
	"\x17proto/system_info.proto\x12\x05sonic\"\x18\n" +
	"\x16GetPlatformTypeRequest\"x\n" +
	"\x17GetPlatformTypeResponse\x12/\n" +
	"\x13platform_identifier\x18\x01 \x01(\tR\x12platformIdentifier\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model2`\n" +
	"\n" +
	"SystemInfo\x12R\n" +
	"\x0fGetPlatformType\x12\x1d.sonic.GetPlatformTypeRequest\x1a\x1e.sonic.GetPlatformTypeResponse\"\x00B7Z5github.com/sonic-net/sonic-gnmi/upgrade-service/protob\x06proto3"

var (
	file_proto_system_info_proto_rawDescOnce sync.Once
	file_proto_system_info_proto_rawDescData []byte
)

func file_proto_system_info_proto_rawDescGZIP() []byte {
	file_proto_system_info_proto_rawDescOnce.Do(func() {
		file_proto_system_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_system_info_proto_rawDesc), len(file_proto_system_info_proto_rawDesc)))
	})
	return file_proto_system_info_proto_rawDescData
}

var file_proto_system_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_system_info_proto_goTypes = []any{
	(*GetPlatformTypeRequest)(nil),  // 0: sonic.GetPlatformTypeRequest
	(*GetPlatformTypeResponse)(nil), // 1: sonic.GetPlatformTypeResponse
}
var file_proto_system_info_proto_depIdxs = []int32{
	0, // 0: sonic.SystemInfo.GetPlatformType:input_type -> sonic.GetPlatformTypeRequest
	1, // 1: sonic.SystemInfo.GetPlatformType:output_type -> sonic.GetPlatformTypeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_system_info_proto_init() }
func file_proto_system_info_proto_init() {
	if File_proto_system_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_system_info_proto_rawDesc), len(file_proto_system_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_system_info_proto_goTypes,
		DependencyIndexes: file_proto_system_info_proto_depIdxs,
		MessageInfos:      file_proto_system_info_proto_msgTypes,
	}.Build()
	File_proto_system_info_proto = out.File
	file_proto_system_info_proto_goTypes = nil
	file_proto_system_info_proto_depIdxs = nil
}
