//
// Copyright 2026 Microsoft Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//

// This file defines a SONiC gNOI service that pulls OCI/ORAS artifacts
// (e.g. SONiC OS images stored in an OCI registry) from a remote registry
// into local storage on the target. See doc/oras-pull-design.md for the
// full design.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: oras.proto

package oras

import (
	context "context"
	_ "github.com/openconfig/gnoi/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. Registry hostname, e.g. "registry.example.com".
	Registry string `protobuf:"bytes,1,opt,name=registry,proto3" json:"registry,omitempty"`
	// Required. Repository within the registry, e.g. "namespace/image".
	Repository string `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	// Required. Exactly one of tag/digest must be set.
	//
	// Types that are assignable to Reference:
	//
	//	*PullRequest_Tag
	//	*PullRequest_Digest
	Reference isPullRequest_Reference `protobuf_oneof:"reference"`
	// Required. Absolute path on the target where the artifact's single layer
	// will be written. Must be under the file-server allowlist (currently
	// /tmp/, /var/tmp/, /host/). Overwritten if it already exists.
	LocalPath string `protobuf:"bytes,5,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	// Auth for the pull. Unset == anonymous.
	Auth *AuthConfig `protobuf:"bytes,6,opt,name=auth,proto3" json:"auth,omitempty"`
	// Optional. HTTP(S) proxy used for the pull, e.g. "http://10.250.0.1:8888".
	// Required on testbeds where the registry is not reachable via the
	// device's default route.
	HttpProxy string `protobuf:"bytes,7,opt,name=http_proxy,json=httpProxy,proto3" json:"http_proxy,omitempty"`
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oras_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oras_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_oras_proto_rawDescGZIP(), []int{0}
}

func (x *PullRequest) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *PullRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (m *PullRequest) GetReference() isPullRequest_Reference {
	if m != nil {
		return m.Reference
	}
	return nil
}

func (x *PullRequest) GetTag() string {
	if x, ok := x.GetReference().(*PullRequest_Tag); ok {
		return x.Tag
	}
	return ""
}

func (x *PullRequest) GetDigest() string {
	if x, ok := x.GetReference().(*PullRequest_Digest); ok {
		return x.Digest
	}
	return ""
}

func (x *PullRequest) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *PullRequest) GetAuth() *AuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *PullRequest) GetHttpProxy() string {
	if x != nil {
		return x.HttpProxy
	}
	return ""
}

type isPullRequest_Reference interface {
	isPullRequest_Reference()
}

type PullRequest_Tag struct {
	Tag string `protobuf:"bytes,3,opt,name=tag,proto3,oneof"` // e.g. "20230531.46"
}

type PullRequest_Digest struct {
	Digest string `protobuf:"bytes,4,opt,name=digest,proto3,oneof"` // e.g. "sha256:6f0923e8…"
}

func (*PullRequest_Tag) isPullRequest_Reference() {}

func (*PullRequest_Digest) isPullRequest_Reference() {}

type AuthConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Mode:
	//
	//	*AuthConfig_Anonymous
	//	*AuthConfig_Basic
	Mode isAuthConfig_Mode `protobuf_oneof:"mode"`
}

func (x *AuthConfig) Reset() {
	*x = AuthConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oras_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfig) ProtoMessage() {}

func (x *AuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_oras_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfig.ProtoReflect.Descriptor instead.
func (*AuthConfig) Descriptor() ([]byte, []int) {
	return file_oras_proto_rawDescGZIP(), []int{1}
}

func (m *AuthConfig) GetMode() isAuthConfig_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (x *AuthConfig) GetAnonymous() *Anonymous {
	if x, ok := x.GetMode().(*AuthConfig_Anonymous); ok {
		return x.Anonymous
	}
	return nil
}

func (x *AuthConfig) GetBasic() *BasicAuth {
	if x, ok := x.GetMode().(*AuthConfig_Basic); ok {
		return x.Basic
	}
	return nil
}

type isAuthConfig_Mode interface {
	isAuthConfig_Mode()
}

type AuthConfig_Anonymous struct {
	// Empty marker for explicit anonymous (otherwise distinguished from
	// "field not set" by oneof semantics).
	Anonymous *Anonymous `protobuf:"bytes,1,opt,name=anonymous,proto3,oneof"`
}

type AuthConfig_Basic struct {
	Basic *BasicAuth `protobuf:"bytes,2,opt,name=basic,proto3,oneof"`
}

func (*AuthConfig_Anonymous) isAuthConfig_Mode() {}

func (*AuthConfig_Basic) isAuthConfig_Mode() {}

type Anonymous struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Anonymous) Reset() {
	*x = Anonymous{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oras_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Anonymous) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anonymous) ProtoMessage() {}

func (x *Anonymous) ProtoReflect() protoreflect.Message {
	mi := &file_oras_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anonymous.ProtoReflect.Descriptor instead.
func (*Anonymous) Descriptor() ([]byte, []int) {
	return file_oras_proto_rawDescGZIP(), []int{2}
}

type BasicAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *BasicAuth) Reset() {
	*x = BasicAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oras_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuth) ProtoMessage() {}

func (x *BasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_oras_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuth.ProtoReflect.Descriptor instead.
func (*BasicAuth) Descriptor() ([]byte, []int) {
	return file_oras_proto_rawDescGZIP(), []int{3}
}

func (x *BasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PullResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*PullResponse_Started
	//	*PullResponse_Progress
	//	*PullResponse_Result
	Event isPullResponse_Event `protobuf_oneof:"event"`
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oras_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oras_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_oras_proto_rawDescGZIP(), []int{4}
}

func (m *PullResponse) GetEvent() isPullResponse_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *PullResponse) GetStarted() *PullStarted {
	if x, ok := x.GetEvent().(*PullResponse_Started); ok {
		return x.Started
	}
	return nil
}

func (x *PullResponse) GetProgress() *PullProgress {
	if x, ok := x.GetEvent().(*PullResponse_Progress); ok {
		return x.Progress
	}
	return nil
}

func (x *PullResponse) GetResult() *PullResult {
	if x, ok := x.GetEvent().(*PullResponse_Result); ok {
		return x.Result
	}
	return nil
}

type isPullResponse_Event interface {
	isPullResponse_Event()
}

type PullResponse_Started struct {
	Started *PullStarted `protobuf:"bytes,1,opt,name=started,proto3,oneof"`
}

type PullResponse_Progress struct {
	Progress *PullProgress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type PullResponse_Result struct {
	Result *PullResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

func (*PullResponse_Started) isPullResponse_Event() {}

func (*PullResponse_Progress) isPullResponse_Event() {}

func (*PullResponse_Result) isPullResponse_Event() {}

type PullStarted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Resolved manifest digest, even if the request used a tag.
	ManifestDigest string `protobuf:"bytes,1,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	// Total bytes the server expects to transfer (size of the selected layer).
	TotalBytes uint64 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
}

func (x *PullStarted) Reset() {
	*x = PullStarted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oras_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullStarted) ProtoMessage() {}

func (x *PullStarted) ProtoReflect() protoreflect.Message {
	mi := &file_oras_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullStarted.ProtoReflect.Descriptor instead.
func (*PullStarted) Descriptor() ([]byte, []int) {
	return file_oras_proto_rawDescGZIP(), []int{5}
}

func (x *PullStarted) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *PullStarted) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type PullProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BytesTransferred uint64 `protobuf:"varint,1,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes       uint64 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
}

func (x *PullProgress) Reset() {
	*x = PullProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oras_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullProgress) ProtoMessage() {}

func (x *PullProgress) ProtoReflect() protoreflect.Message {
	mi := &file_oras_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullProgress.ProtoReflect.Descriptor instead.
func (*PullProgress) Descriptor() ([]byte, []int) {
	return file_oras_proto_rawDescGZIP(), []int{6}
}

func (x *PullProgress) GetBytesTransferred() uint64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *PullProgress) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type PullResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Resolved manifest digest.
	ManifestDigest string `protobuf:"bytes,1,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	// Digest of the layer that was written.
	LayerDigest string `protobuf:"bytes,2,opt,name=layer_digest,json=layerDigest,proto3" json:"layer_digest,omitempty"`
	// Size in bytes of the layer that was written.
	BytesWritten uint64 `protobuf:"varint,3,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	// Absolute path on the target where the layer was written. Equal to
	// PullRequest.local_path.
	LocalPath string `protobuf:"bytes,4,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	// Wall-clock time from PullStarted to PullResult.
	Elapsed *durationpb.Duration `protobuf:"bytes,5,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
}

func (x *PullResult) Reset() {
	*x = PullResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_oras_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResult) ProtoMessage() {}

func (x *PullResult) ProtoReflect() protoreflect.Message {
	mi := &file_oras_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResult.ProtoReflect.Descriptor instead.
func (*PullResult) Descriptor() ([]byte, []int) {
	return file_oras_proto_rawDescGZIP(), []int{7}
}

func (x *PullResult) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *PullResult) GetLayerDigest() string {
	if x != nil {
		return x.LayerDigest
	}
	return ""
}

func (x *PullResult) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *PullResult) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *PullResult) GetElapsed() *durationpb.Duration {
	if x != nil {
		return x.Elapsed
	}
	return nil
}

var File_oras_proto protoreflect.FileDescriptor

var file_oras_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x6f,
	0x6e, 0x69, 0x63, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31,
	0x1a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6e, 0x6f, 0x69, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6,
	0x01, 0x0a, 0x0b, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18,
	0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61,
	0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x32, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x67, 0x6e,
	0x6f, 0x69, 0x2e, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x68,
	0x74, 0x74, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x68, 0x74, 0x74, 0x70, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x42, 0x0b, 0x0a, 0x09, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x3d, 0x0a, 0x09, 0x61, 0x6e, 0x6f, 0x6e, 0x79, 0x6d,
	0x6f, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x6f, 0x6e, 0x69,
	0x63, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x48, 0x00, 0x52, 0x09, 0x61, 0x6e, 0x6f, 0x6e,
	0x79, 0x6d, 0x6f, 0x75, 0x73, 0x12, 0x35, 0x0a, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x67, 0x6e, 0x6f,
	0x69, 0x2e, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41,
	0x75, 0x74, 0x68, 0x48, 0x00, 0x52, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x42, 0x06, 0x0a, 0x04,
	0x6d, 0x6f, 0x64, 0x65, 0x22, 0x0b, 0x0a, 0x09, 0x41, 0x6e, 0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75,
	0x73, 0x22, 0x43, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x69, 0x63, 0x41, 0x75, 0x74, 0x68, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0xce, 0x01, 0x0a, 0x0c, 0x50, 0x75, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63,
	0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75,
	0x6c, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x65, 0x64, 0x12, 0x3e, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x67,
	0x6e, 0x6f, 0x69, 0x2e, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x6c, 0x6c,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x67, 0x6e, 0x6f,
	0x69, 0x2e, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x07,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x57, 0x0a, 0x0b, 0x50, 0x75, 0x6c, 0x6c, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x22, 0x5c, 0x0a, 0x0c, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x2b, 0x0a, 0x11, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x65, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0xd1,
	0x01, 0x0a, 0x0a, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a,
	0x0f, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74,
	0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0c, 0x62, 0x79, 0x74, 0x65, 0x73, 0x57, 0x72, 0x69, 0x74, 0x74, 0x65, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x50, 0x61, 0x74, 0x68, 0x12, 0x33, 0x0a,
	0x07, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x65, 0x6c, 0x61, 0x70, 0x73,
	0x65, 0x64, 0x32, 0x53, 0x0a, 0x04, 0x4f, 0x72, 0x61, 0x73, 0x12, 0x4b, 0x0a, 0x04, 0x50, 0x75,
	0x6c, 0x6c, 0x12, 0x1f, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x67, 0x6e, 0x6f, 0x69, 0x2e,
	0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x73, 0x6f, 0x6e, 0x69, 0x63, 0x2e, 0x67, 0x6e, 0x6f, 0x69,
	0x2e, 0x6f, 0x72, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x11, 0xd2, 0x3e, 0x05, 0x30, 0x2e, 0x31, 0x2e,
	0x30, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x6f, 0x72, 0x61, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_oras_proto_rawDescOnce sync.Once
	file_oras_proto_rawDescData = file_oras_proto_rawDesc
)

func file_oras_proto_rawDescGZIP() []byte {
	file_oras_proto_rawDescOnce.Do(func() {
		file_oras_proto_rawDescData = protoimpl.X.CompressGZIP(file_oras_proto_rawDescData)
	})
	return file_oras_proto_rawDescData
}

var file_oras_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_oras_proto_goTypes = []interface{}{
	(*PullRequest)(nil),         // 0: sonic.gnoi.oras.v1.PullRequest
	(*AuthConfig)(nil),          // 1: sonic.gnoi.oras.v1.AuthConfig
	(*Anonymous)(nil),           // 2: sonic.gnoi.oras.v1.Anonymous
	(*BasicAuth)(nil),           // 3: sonic.gnoi.oras.v1.BasicAuth
	(*PullResponse)(nil),        // 4: sonic.gnoi.oras.v1.PullResponse
	(*PullStarted)(nil),         // 5: sonic.gnoi.oras.v1.PullStarted
	(*PullProgress)(nil),        // 6: sonic.gnoi.oras.v1.PullProgress
	(*PullResult)(nil),          // 7: sonic.gnoi.oras.v1.PullResult
	(*durationpb.Duration)(nil), // 8: google.protobuf.Duration
}
var file_oras_proto_depIdxs = []int32{
	1, // 0: sonic.gnoi.oras.v1.PullRequest.auth:type_name -> sonic.gnoi.oras.v1.AuthConfig
	2, // 1: sonic.gnoi.oras.v1.AuthConfig.anonymous:type_name -> sonic.gnoi.oras.v1.Anonymous
	3, // 2: sonic.gnoi.oras.v1.AuthConfig.basic:type_name -> sonic.gnoi.oras.v1.BasicAuth
	5, // 3: sonic.gnoi.oras.v1.PullResponse.started:type_name -> sonic.gnoi.oras.v1.PullStarted
	6, // 4: sonic.gnoi.oras.v1.PullResponse.progress:type_name -> sonic.gnoi.oras.v1.PullProgress
	7, // 5: sonic.gnoi.oras.v1.PullResponse.result:type_name -> sonic.gnoi.oras.v1.PullResult
	8, // 6: sonic.gnoi.oras.v1.PullResult.elapsed:type_name -> google.protobuf.Duration
	0, // 7: sonic.gnoi.oras.v1.Oras.Pull:input_type -> sonic.gnoi.oras.v1.PullRequest
	4, // 8: sonic.gnoi.oras.v1.Oras.Pull:output_type -> sonic.gnoi.oras.v1.PullResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_oras_proto_init() }
func file_oras_proto_init() {
	if File_oras_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_oras_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oras_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oras_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Anonymous); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oras_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oras_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oras_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullStarted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oras_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_oras_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_oras_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*PullRequest_Tag)(nil),
		(*PullRequest_Digest)(nil),
	}
	file_oras_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*AuthConfig_Anonymous)(nil),
		(*AuthConfig_Basic)(nil),
	}
	file_oras_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*PullResponse_Started)(nil),
		(*PullResponse_Progress)(nil),
		(*PullResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oras_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oras_proto_goTypes,
		DependencyIndexes: file_oras_proto_depIdxs,
		MessageInfos:      file_oras_proto_msgTypes,
	}.Build()
	File_oras_proto = out.File
	file_oras_proto_rawDesc = nil
	file_oras_proto_goTypes = nil
	file_oras_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrasClient is the client API for Oras service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrasClient interface {
	// Pull fetches an OCI/ORAS artifact from a registry into a local file on
	// the target. The response stream emits a single PullStarted message once
	// the manifest is resolved, zero or more PullProgress messages while bytes
	// are being transferred, and a final PullResult on success.
	//
	// Errors (gRPC status codes):
	//
	//	InvalidArgument:    missing required fields, unsupported layer count
	//	                    for the PoC (must be exactly one).
	//	Unauthenticated:    registry rejected the supplied credentials.
	//	FailedPrecondition: resolved manifest digest mismatch or destination
	//	                    path outside the allowlist.
	//	Unavailable:        registry unreachable (DNS/TCP/timeout).
	//	ResourceExhausted:  disk full while writing.
	//	DataLoss:           digest verification failed after download.
	//	Internal:           anything else.
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (Oras_PullClient, error)
}

type orasClient struct {
	cc grpc.ClientConnInterface
}

func NewOrasClient(cc grpc.ClientConnInterface) OrasClient {
	return &orasClient{cc}
}

func (c *orasClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (Oras_PullClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Oras_serviceDesc.Streams[0], "/sonic.gnoi.oras.v1.Oras/Pull", opts...)
	if err != nil {
		return nil, err
	}
	x := &orasPullClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Oras_PullClient interface {
	Recv() (*PullResponse, error)
	grpc.ClientStream
}

type orasPullClient struct {
	grpc.ClientStream
}

func (x *orasPullClient) Recv() (*PullResponse, error) {
	m := new(PullResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrasServer is the server API for Oras service.
type OrasServer interface {
	// Pull fetches an OCI/ORAS artifact from a registry into a local file on
	// the target. The response stream emits a single PullStarted message once
	// the manifest is resolved, zero or more PullProgress messages while bytes
	// are being transferred, and a final PullResult on success.
	//
	// Errors (gRPC status codes):
	//
	//	InvalidArgument:    missing required fields, unsupported layer count
	//	                    for the PoC (must be exactly one).
	//	Unauthenticated:    registry rejected the supplied credentials.
	//	FailedPrecondition: resolved manifest digest mismatch or destination
	//	                    path outside the allowlist.
	//	Unavailable:        registry unreachable (DNS/TCP/timeout).
	//	ResourceExhausted:  disk full while writing.
	//	DataLoss:           digest verification failed after download.
	//	Internal:           anything else.
	Pull(*PullRequest, Oras_PullServer) error
}

// UnimplementedOrasServer can be embedded to have forward compatible implementations.
type UnimplementedOrasServer struct {
}

func (*UnimplementedOrasServer) Pull(*PullRequest, Oras_PullServer) error {
	return status.Errorf(codes.Unimplemented, "method Pull not implemented")
}

func RegisterOrasServer(s *grpc.Server, srv OrasServer) {
	s.RegisterService(&_Oras_serviceDesc, srv)
}

func _Oras_Pull_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PullRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrasServer).Pull(m, &orasPullServer{stream})
}

type Oras_PullServer interface {
	Send(*PullResponse) error
	grpc.ServerStream
}

type orasPullServer struct {
	grpc.ServerStream
}

func (x *orasPullServer) Send(m *PullResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Oras_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sonic.gnoi.oras.v1.Oras",
	HandlerType: (*OrasServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pull",
			Handler:       _Oras_Pull_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "oras.proto",
}
