// Code generated by protoc-gen-go. DO NOT EDIT.
// source: port_stat.proto

/*
Package gnmi_sonic is a generated protocol buffer package.

It is generated from these files:
	port_stat.proto
	sonic.proto
	sonic_internal.proto

It has these top-level messages:
	Value
*/
package gnmi_sonic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/openconfig/gnmi/proto/gnmi"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CountersTableT int32

const (
	CountersTableT_COUNTERS_PORT_NAME_MAP   CountersTableT = 0
	CountersTableT_COUNTERS                 CountersTableT = 1
	CountersTableT_COUNTERS_QUEUE_NAME_MAP  CountersTableT = 2
	CountersTableT_COUNTERS_QUEUE_PORT_MAP  CountersTableT = 3
	CountersTableT_COUNTERS_QUEUE_INDEX_MAP CountersTableT = 4
	CountersTableT_COUNTERS_QUEUE_TYPE_MAP  CountersTableT = 5
)

var CountersTableT_name = map[int32]string{
	0: "COUNTERS_PORT_NAME_MAP",
	1: "COUNTERS",
	2: "COUNTERS_QUEUE_NAME_MAP",
	3: "COUNTERS_QUEUE_PORT_MAP",
	4: "COUNTERS_QUEUE_INDEX_MAP",
	5: "COUNTERS_QUEUE_TYPE_MAP",
}
var CountersTableT_value = map[string]int32{
	"COUNTERS_PORT_NAME_MAP":   0,
	"COUNTERS":                 1,
	"COUNTERS_QUEUE_NAME_MAP":  2,
	"COUNTERS_QUEUE_PORT_MAP":  3,
	"COUNTERS_QUEUE_INDEX_MAP": 4,
	"COUNTERS_QUEUE_TYPE_MAP":  5,
}

func (x CountersTableT) String() string {
	return proto.EnumName(CountersTableT_name, int32(x))
}
func (CountersTableT) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SaiPortStatT int32

const (
	// * SAI port stat if in octets
	SaiPortStatT_SAI_PORT_STAT_IF_IN_OCTETS SaiPortStatT = 0
	// * SAI port stat if in ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IF_IN_UCAST_PKTS SaiPortStatT = 1
	// * SAI port stat if in non ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IF_IN_NON_UCAST_PKTS SaiPortStatT = 2
	// * SAI port stat if in discards
	SaiPortStatT_SAI_PORT_STAT_IF_IN_DISCARDS SaiPortStatT = 3
	// * SAI port stat if in errors
	SaiPortStatT_SAI_PORT_STAT_IF_IN_ERRORS SaiPortStatT = 4
	// * SAI port stat if in unknown protocols
	SaiPortStatT_SAI_PORT_STAT_IF_IN_UNKNOWN_PROTOS SaiPortStatT = 5
	// * SAI port stat if in broadcast pkts
	SaiPortStatT_SAI_PORT_STAT_IF_IN_BROADCAST_PKTS SaiPortStatT = 6
	// * SAI port stat if in multicast pkts
	SaiPortStatT_SAI_PORT_STAT_IF_IN_MULTICAST_PKTS SaiPortStatT = 7
	// * SAI port stat if in vlan discards
	SaiPortStatT_SAI_PORT_STAT_IF_IN_VLAN_DISCARDS SaiPortStatT = 8
	// * SAI port stat if out octets
	SaiPortStatT_SAI_PORT_STAT_IF_OUT_OCTETS SaiPortStatT = 9
	// * SAI port stat if out ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IF_OUT_UCAST_PKTS SaiPortStatT = 10
	// * SAI port stat if out non ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IF_OUT_NON_UCAST_PKTS SaiPortStatT = 11
	// * SAI port stat if out discards
	SaiPortStatT_SAI_PORT_STAT_IF_OUT_DISCARDS SaiPortStatT = 12
	// * SAI port stat if out errors
	SaiPortStatT_SAI_PORT_STAT_IF_OUT_ERRORS SaiPortStatT = 13
	// * SAI port stat if out queue length
	SaiPortStatT_SAI_PORT_STAT_IF_OUT_QLEN SaiPortStatT = 14
	// * SAI port stat if out broadcast pkts
	SaiPortStatT_SAI_PORT_STAT_IF_OUT_BROADCAST_PKTS SaiPortStatT = 15
	// * SAI port stat if out multicast pkts
	SaiPortStatT_SAI_PORT_STAT_IF_OUT_MULTICAST_PKTS SaiPortStatT = 16
	// * SAI port stat ether stats drop events
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_DROP_EVENTS SaiPortStatT = 17
	// * SAI port stat ether stats multicast pkts
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_MULTICAST_PKTS SaiPortStatT = 18
	// * SAI port stat ether stats broadcast pkts
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_BROADCAST_PKTS SaiPortStatT = 19
	// * SAI port stat ether stats undersized pkts
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_UNDERSIZE_PKTS SaiPortStatT = 20
	// * SAI port stat ether stats fragments
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_FRAGMENTS SaiPortStatT = 21
	// * SAI port stat ether stats pkts 64 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_64_OCTETS SaiPortStatT = 22
	// * SAI port stat ether stats pkts 65 to 127 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_65_TO_127_OCTETS SaiPortStatT = 23
	// * SAI port stat ether stats pkts 128 to 255 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_128_TO_255_OCTETS SaiPortStatT = 24
	// * SAI port stat ether stats pkts 256 to 511 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_256_TO_511_OCTETS SaiPortStatT = 25
	// * SAI port stat ether stats pkts 512 to 1023 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_512_TO_1023_OCTETS SaiPortStatT = 26
	// * SAI port stat ether stats pkts 1024 to 1518 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_1024_TO_1518_OCTETS SaiPortStatT = 27
	// * SAI port stat ether stats pkts 1519 to 2047 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_1519_TO_2047_OCTETS SaiPortStatT = 28
	// * SAI port stat ether stats pkts 2048 to 4095 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_2048_TO_4095_OCTETS SaiPortStatT = 29
	// * SAI port stat ether stats pkts 4096 to 9216 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_4096_TO_9216_OCTETS SaiPortStatT = 30
	// * SAI port stat ether stats pkts 9217 to 16383 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS_9217_TO_16383_OCTETS SaiPortStatT = 31
	// * SAI port stat ether stats oversize pkts
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_OVERSIZE_PKTS SaiPortStatT = 32
	// * SAI port stat ether rx oversize pkts
	SaiPortStatT_SAI_PORT_STAT_ETHER_RX_OVERSIZE_PKTS SaiPortStatT = 33
	// * SAI port stat ether tx oversize pkts
	SaiPortStatT_SAI_PORT_STAT_ETHER_TX_OVERSIZE_PKTS SaiPortStatT = 34
	// * SAI port stat ether stats jabbers
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_JABBERS SaiPortStatT = 35
	// * SAI port stat ether stats octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_OCTETS SaiPortStatT = 36
	// * SAI port stat ether stats pkts
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_PKTS SaiPortStatT = 37
	// * SAI port stat ether stats collisions
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_COLLISIONS SaiPortStatT = 38
	// * SAI port stat ether stats CRC align errors
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_CRC_ALIGN_ERRORS SaiPortStatT = 39
	// * SAI port stat ether stats tx no errors
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_TX_NO_ERRORS SaiPortStatT = 40
	// * SAI port stat ether stats rx no errors
	SaiPortStatT_SAI_PORT_STAT_ETHER_STATS_RX_NO_ERRORS SaiPortStatT = 41
	// * SAI port stat IP in receives
	SaiPortStatT_SAI_PORT_STAT_IP_IN_RECEIVES SaiPortStatT = 42
	// * SAI port stat IP in octets
	SaiPortStatT_SAI_PORT_STAT_IP_IN_OCTETS SaiPortStatT = 43
	// * SAI port stat IP in ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IP_IN_UCAST_PKTS SaiPortStatT = 44
	// * SAI port stat IP in non ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IP_IN_NON_UCAST_PKTS SaiPortStatT = 45
	// * SAI port stat IP in discards
	SaiPortStatT_SAI_PORT_STAT_IP_IN_DISCARDS SaiPortStatT = 46
	// * SAI port stat IP out octets
	SaiPortStatT_SAI_PORT_STAT_IP_OUT_OCTETS SaiPortStatT = 47
	// * SAI port stat IP out ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IP_OUT_UCAST_PKTS SaiPortStatT = 48
	// * SAI port stat IP out non ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IP_OUT_NON_UCAST_PKTS SaiPortStatT = 49
	// * SAI port stat IP out discards
	SaiPortStatT_SAI_PORT_STAT_IP_OUT_DISCARDS SaiPortStatT = 50
	// * SAI port stat IPv6 in receives
	SaiPortStatT_SAI_PORT_STAT_IPV6_IN_RECEIVES SaiPortStatT = 51
	// * SAI port stat IPv6 in octets
	SaiPortStatT_SAI_PORT_STAT_IPV6_IN_OCTETS SaiPortStatT = 52
	// * SAI port stat IPv6 in ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IPV6_IN_UCAST_PKTS SaiPortStatT = 53
	// * SAI port stat IPv6 in non ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IPV6_IN_NON_UCAST_PKTS SaiPortStatT = 54
	// * SAI port stat IPv6 in mcast pkts
	SaiPortStatT_SAI_PORT_STAT_IPV6_IN_MCAST_PKTS SaiPortStatT = 55
	// * SAI port stat IPv6 in discards
	SaiPortStatT_SAI_PORT_STAT_IPV6_IN_DISCARDS SaiPortStatT = 56
	// * SAI port stat IPv6 out octets
	SaiPortStatT_SAI_PORT_STAT_IPV6_OUT_OCTETS SaiPortStatT = 57
	// * SAI port stat IPv6 out ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IPV6_OUT_UCAST_PKTS SaiPortStatT = 58
	// * SAI port stat IPv6 out non ucast pkts
	SaiPortStatT_SAI_PORT_STAT_IPV6_OUT_NON_UCAST_PKTS SaiPortStatT = 59
	// * SAI port stat IPv6 out mcast pkts
	SaiPortStatT_SAI_PORT_STAT_IPV6_OUT_MCAST_PKTS SaiPortStatT = 60
	// * SAI port stat IPv6 out discards
	SaiPortStatT_SAI_PORT_STAT_IPV6_OUT_DISCARDS SaiPortStatT = 61
	// * Get/set WRED green packet count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_GREEN_WRED_DROPPED_PACKETS SaiPortStatT = 62
	// * Get/set WRED green byte count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_GREEN_WRED_DROPPED_BYTES SaiPortStatT = 63
	// * Get/set WRED yellow packet count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_YELLOW_WRED_DROPPED_PACKETS SaiPortStatT = 64
	// * Get/set WRED yellow byte count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_YELLOW_WRED_DROPPED_BYTES SaiPortStatT = 65
	// * Get/set WRED red packet count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_RED_WRED_DROPPED_PACKETS SaiPortStatT = 66
	// * Get/set WRED red byte count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_RED_WRED_DROPPED_BYTES SaiPortStatT = 67
	// * Get/set WRED dropped packets count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_WRED_DROPPED_PACKETS SaiPortStatT = 68
	// * Get/set WRED dropped bytes count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_WRED_DROPPED_BYTES SaiPortStatT = 69
	// * Get/set packets marked by ECN count [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_ECN_MARKED_PACKETS SaiPortStatT = 70
	// * Packet size based packets count rt stat ether in pkts 64 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_64_OCTETS SaiPortStatT = 71
	// * SAI port stat ether in pkts 65 to 127 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_65_TO_127_OCTETS SaiPortStatT = 72
	// * SAI port stat ether in pkts 128 to 255 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_128_TO_255_OCTETS SaiPortStatT = 73
	// * SAI port stat ether in pkts 256 to 511 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_256_TO_511_OCTETS SaiPortStatT = 74
	// * SAI port stat ether in pkts 512 to 1023 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_512_TO_1023_OCTETS SaiPortStatT = 75
	// * SAI port stat ether in pkts 1024 to 1518 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_1024_TO_1518_OCTETS SaiPortStatT = 76
	// * SAI port stat ether in pkts 1519 to 2047 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_1519_TO_2047_OCTETS SaiPortStatT = 77
	// * SAI port stat ether in pkts 2048 to 4095 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_2048_TO_4095_OCTETS SaiPortStatT = 78
	// * SAI port stat ether in pkts 4096 to 9216 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_4096_TO_9216_OCTETS SaiPortStatT = 79
	// * SAI port stat ether in pkts 9217 to 16383 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_IN_PKTS_9217_TO_16383_OCTETS SaiPortStatT = 80
	// * SAI port stat ether out pkts 64 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_64_OCTETS SaiPortStatT = 81
	// * SAI port stat ether out pkts 65 to 127 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_65_TO_127_OCTETS SaiPortStatT = 82
	// * SAI port stat ether out pkts 128 to 255 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_128_TO_255_OCTETS SaiPortStatT = 83
	// * SAI port stat ether out pkts 256 to 511 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_256_TO_511_OCTETS SaiPortStatT = 84
	// * SAI port stat ether out pkts 512 to 1023 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_512_TO_1023_OCTETS SaiPortStatT = 85
	// * SAI port stat ether out pkts 1024 to 1518 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_1024_TO_1518_OCTETS SaiPortStatT = 86
	// * SAI port stat ether out pkts 1519 to 2047 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_1519_TO_2047_OCTETS SaiPortStatT = 87
	// * SAI port stat ether out pkts 2048 to 4095 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_2048_TO_4095_OCTETS SaiPortStatT = 88
	// * SAI port stat ether out pkts 4096 to 9216 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_4096_TO_9216_OCTETS SaiPortStatT = 89
	// * SAI port stat ether out pkts 9217 to 16383 octets
	SaiPortStatT_SAI_PORT_STAT_ETHER_OUT_PKTS_9217_TO_16383_OCTETS SaiPortStatT = 90
	// * Get in port current occupancy in bytes [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_IN_CURR_OCCUPANCY_BYTES SaiPortStatT = 91
	// * Get in port watermark occupancy in bytes [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_IN_WATERMARK_BYTES SaiPortStatT = 92
	// * Get in port current shared occupancy in bytes [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_IN_SHARED_CURR_OCCUPANCY_BYTES SaiPortStatT = 93
	// * Get in port watermark shared occupancy in bytes [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_IN_SHARED_WATERMARK_BYTES SaiPortStatT = 94
	// * Get out port current occupancy in bytes [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_OUT_CURR_OCCUPANCY_BYTES SaiPortStatT = 95
	// * Get out port watermark occupancy in bytes [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_OUT_WATERMARK_BYTES SaiPortStatT = 96
	// * Get out port current shared occupancy in bytes [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_OUT_SHARED_CURR_OCCUPANCY_BYTES SaiPortStatT = 97
	// * Get out port watermark shared occupancy in bytes [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_OUT_SHARED_WATERMARK_BYTES SaiPortStatT = 98
	// * Get in port packet drops due to buffers [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_IN_DROPPED_PKTS SaiPortStatT = 99
	// * Get out port packet drops due to buffers [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_OUT_DROPPED_PKTS SaiPortStatT = 100
	// * Get the number of pause frames received on the port [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_PAUSE_RX_PKTS SaiPortStatT = 101
	// * Get the number of pause frames transmitted on the port [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_PAUSE_TX_PKTS SaiPortStatT = 102
	// * PFC Packet Counters for RX and TX per PFC priority [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_PFC_0_RX_PKTS SaiPortStatT = 103
	// * SAI port stat PFC 0 tx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_0_TX_PKTS SaiPortStatT = 104
	// * SAI port stat PFC 1 rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_1_RX_PKTS SaiPortStatT = 105
	// * SAI port stat PFC 1 tx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_1_TX_PKTS SaiPortStatT = 106
	// * SAI port stat PFC 2 rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_2_RX_PKTS SaiPortStatT = 107
	// * SAI port stat PFC 2 tx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_2_TX_PKTS SaiPortStatT = 108
	// * SAI port stat PFC 3 rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_3_RX_PKTS SaiPortStatT = 109
	// * SAI port stat PFC 3 tx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_3_TX_PKTS SaiPortStatT = 110
	// * SAI port stat PFC 4 rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_4_RX_PKTS SaiPortStatT = 111
	// * SAI port stat PFC 4 tx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_4_TX_PKTS SaiPortStatT = 112
	// * SAI port stat PFC 5 rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_5_RX_PKTS SaiPortStatT = 113
	// * SAI port stat PFC 5 tx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_5_TX_PKTS SaiPortStatT = 114
	// * SAI port stat PFC 6 rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_6_RX_PKTS SaiPortStatT = 115
	// * SAI port stat PFC 6 tx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_6_TX_PKTS SaiPortStatT = 116
	// * SAI port stat PFC 7 rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_7_RX_PKTS SaiPortStatT = 117
	// * SAI port stat PFC 7 tx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_7_TX_PKTS SaiPortStatT = 118
	// *
	// @brief PFC pause duration for RX and TX per PFC priority [uint64_t]
	//
	// RX pause duration for certain priority is a the duration quanta in ingress pause
	// frame for that priority (a pause frame received by the switch).
	// While TX pause duration for certain priority is the duration quanta in egress pause
	// frame for that priority (a pause frame sent by the switch).
	SaiPortStatT_SAI_PORT_STAT_PFC_0_RX_PAUSE_DURATION SaiPortStatT = 119
	// * SAI port stat PFC 0 tx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_0_TX_PAUSE_DURATION SaiPortStatT = 120
	// * SAI port stat PFC 1 rx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_1_RX_PAUSE_DURATION SaiPortStatT = 121
	// * SAI port stat PFC 1 tx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_1_TX_PAUSE_DURATION SaiPortStatT = 122
	// * SAI port stat PFC 2 rx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_2_RX_PAUSE_DURATION SaiPortStatT = 123
	// * SAI port stat PFC 2 tx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_2_TX_PAUSE_DURATION SaiPortStatT = 124
	// * SAI port stat PFC 3 rx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_3_RX_PAUSE_DURATION SaiPortStatT = 125
	// * SAI port stat PFC 3 tx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_3_TX_PAUSE_DURATION SaiPortStatT = 126
	// * SAI port stat PFC 4 rx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_4_RX_PAUSE_DURATION SaiPortStatT = 127
	// * SAI port stat PFC 4 tx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_4_TX_PAUSE_DURATION SaiPortStatT = 128
	// * SAI port stat PFC 5 rx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_5_RX_PAUSE_DURATION SaiPortStatT = 129
	// * SAI port stat PFC 5 tx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_5_TX_PAUSE_DURATION SaiPortStatT = 130
	// * SAI port stat PFC 6 rx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_6_RX_PAUSE_DURATION SaiPortStatT = 131
	// * SAI port stat PFC 6 tx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_6_TX_PAUSE_DURATION SaiPortStatT = 132
	// * SAI port stat PFC 7 rx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_7_RX_PAUSE_DURATION SaiPortStatT = 133
	// * SAI port stat PFC 7 tx duration
	SaiPortStatT_SAI_PORT_STAT_PFC_7_TX_PAUSE_DURATION SaiPortStatT = 134
	// * PFC based ON to OFF pause transitions counter per PFC priority [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_PFC_0_ON2OFF_RX_PKTS SaiPortStatT = 135
	// * SAI port stat PFC 1 on to off rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_1_ON2OFF_RX_PKTS SaiPortStatT = 136
	// * SAI port stat PFC 2 on to off rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_2_ON2OFF_RX_PKTS SaiPortStatT = 137
	// * SAI port stat PFC 3 on to off rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_3_ON2OFF_RX_PKTS SaiPortStatT = 138
	// * SAI port stat PFC 4 on to off rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_4_ON2OFF_RX_PKTS SaiPortStatT = 139
	// * SAI port stat PFC 5 on to off rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_5_ON2OFF_RX_PKTS SaiPortStatT = 140
	// * SAI port stat PFC 6 on to off rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_6_ON2OFF_RX_PKTS SaiPortStatT = 141
	// * SAI port stat PFC 7 on to off rx pkts
	SaiPortStatT_SAI_PORT_STAT_PFC_7_ON2OFF_RX_PKTS SaiPortStatT = 142
	// *
	// @brief Number of times port state changed from
	// high power mode to low power mode in TX direction [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_EEE_TX_EVENT_COUNT SaiPortStatT = 143
	// *
	// @brief Number of times port state changed from
	// high power mode to low power mode in RX direction [uint64_t]
	SaiPortStatT_SAI_PORT_STAT_EEE_RX_EVENT_COUNT SaiPortStatT = 144
	// *
	// @brief Port Low power mode duration(micro secs) in TX direction [uint64_t].
	//
	// This Duration is accumulative since EEE enable on port/from last clear stats.
	SaiPortStatT_SAI_PORT_STAT_EEE_TX_DURATION SaiPortStatT = 145
	// *
	// @brief Port Low power mode duration(micro secs) in RX direction [uint64_t]
	//
	// This Duration is accumulative since EEE enable on port/from last clear stats.
	SaiPortStatT_SAI_PORT_STAT_EEE_RX_DURATION SaiPortStatT = 146
)

var SaiPortStatT_name = map[int32]string{
	0:   "SAI_PORT_STAT_IF_IN_OCTETS",
	1:   "SAI_PORT_STAT_IF_IN_UCAST_PKTS",
	2:   "SAI_PORT_STAT_IF_IN_NON_UCAST_PKTS",
	3:   "SAI_PORT_STAT_IF_IN_DISCARDS",
	4:   "SAI_PORT_STAT_IF_IN_ERRORS",
	5:   "SAI_PORT_STAT_IF_IN_UNKNOWN_PROTOS",
	6:   "SAI_PORT_STAT_IF_IN_BROADCAST_PKTS",
	7:   "SAI_PORT_STAT_IF_IN_MULTICAST_PKTS",
	8:   "SAI_PORT_STAT_IF_IN_VLAN_DISCARDS",
	9:   "SAI_PORT_STAT_IF_OUT_OCTETS",
	10:  "SAI_PORT_STAT_IF_OUT_UCAST_PKTS",
	11:  "SAI_PORT_STAT_IF_OUT_NON_UCAST_PKTS",
	12:  "SAI_PORT_STAT_IF_OUT_DISCARDS",
	13:  "SAI_PORT_STAT_IF_OUT_ERRORS",
	14:  "SAI_PORT_STAT_IF_OUT_QLEN",
	15:  "SAI_PORT_STAT_IF_OUT_BROADCAST_PKTS",
	16:  "SAI_PORT_STAT_IF_OUT_MULTICAST_PKTS",
	17:  "SAI_PORT_STAT_ETHER_STATS_DROP_EVENTS",
	18:  "SAI_PORT_STAT_ETHER_STATS_MULTICAST_PKTS",
	19:  "SAI_PORT_STAT_ETHER_STATS_BROADCAST_PKTS",
	20:  "SAI_PORT_STAT_ETHER_STATS_UNDERSIZE_PKTS",
	21:  "SAI_PORT_STAT_ETHER_STATS_FRAGMENTS",
	22:  "SAI_PORT_STAT_ETHER_STATS_PKTS_64_OCTETS",
	23:  "SAI_PORT_STAT_ETHER_STATS_PKTS_65_TO_127_OCTETS",
	24:  "SAI_PORT_STAT_ETHER_STATS_PKTS_128_TO_255_OCTETS",
	25:  "SAI_PORT_STAT_ETHER_STATS_PKTS_256_TO_511_OCTETS",
	26:  "SAI_PORT_STAT_ETHER_STATS_PKTS_512_TO_1023_OCTETS",
	27:  "SAI_PORT_STAT_ETHER_STATS_PKTS_1024_TO_1518_OCTETS",
	28:  "SAI_PORT_STAT_ETHER_STATS_PKTS_1519_TO_2047_OCTETS",
	29:  "SAI_PORT_STAT_ETHER_STATS_PKTS_2048_TO_4095_OCTETS",
	30:  "SAI_PORT_STAT_ETHER_STATS_PKTS_4096_TO_9216_OCTETS",
	31:  "SAI_PORT_STAT_ETHER_STATS_PKTS_9217_TO_16383_OCTETS",
	32:  "SAI_PORT_STAT_ETHER_STATS_OVERSIZE_PKTS",
	33:  "SAI_PORT_STAT_ETHER_RX_OVERSIZE_PKTS",
	34:  "SAI_PORT_STAT_ETHER_TX_OVERSIZE_PKTS",
	35:  "SAI_PORT_STAT_ETHER_STATS_JABBERS",
	36:  "SAI_PORT_STAT_ETHER_STATS_OCTETS",
	37:  "SAI_PORT_STAT_ETHER_STATS_PKTS",
	38:  "SAI_PORT_STAT_ETHER_STATS_COLLISIONS",
	39:  "SAI_PORT_STAT_ETHER_STATS_CRC_ALIGN_ERRORS",
	40:  "SAI_PORT_STAT_ETHER_STATS_TX_NO_ERRORS",
	41:  "SAI_PORT_STAT_ETHER_STATS_RX_NO_ERRORS",
	42:  "SAI_PORT_STAT_IP_IN_RECEIVES",
	43:  "SAI_PORT_STAT_IP_IN_OCTETS",
	44:  "SAI_PORT_STAT_IP_IN_UCAST_PKTS",
	45:  "SAI_PORT_STAT_IP_IN_NON_UCAST_PKTS",
	46:  "SAI_PORT_STAT_IP_IN_DISCARDS",
	47:  "SAI_PORT_STAT_IP_OUT_OCTETS",
	48:  "SAI_PORT_STAT_IP_OUT_UCAST_PKTS",
	49:  "SAI_PORT_STAT_IP_OUT_NON_UCAST_PKTS",
	50:  "SAI_PORT_STAT_IP_OUT_DISCARDS",
	51:  "SAI_PORT_STAT_IPV6_IN_RECEIVES",
	52:  "SAI_PORT_STAT_IPV6_IN_OCTETS",
	53:  "SAI_PORT_STAT_IPV6_IN_UCAST_PKTS",
	54:  "SAI_PORT_STAT_IPV6_IN_NON_UCAST_PKTS",
	55:  "SAI_PORT_STAT_IPV6_IN_MCAST_PKTS",
	56:  "SAI_PORT_STAT_IPV6_IN_DISCARDS",
	57:  "SAI_PORT_STAT_IPV6_OUT_OCTETS",
	58:  "SAI_PORT_STAT_IPV6_OUT_UCAST_PKTS",
	59:  "SAI_PORT_STAT_IPV6_OUT_NON_UCAST_PKTS",
	60:  "SAI_PORT_STAT_IPV6_OUT_MCAST_PKTS",
	61:  "SAI_PORT_STAT_IPV6_OUT_DISCARDS",
	62:  "SAI_PORT_STAT_GREEN_WRED_DROPPED_PACKETS",
	63:  "SAI_PORT_STAT_GREEN_WRED_DROPPED_BYTES",
	64:  "SAI_PORT_STAT_YELLOW_WRED_DROPPED_PACKETS",
	65:  "SAI_PORT_STAT_YELLOW_WRED_DROPPED_BYTES",
	66:  "SAI_PORT_STAT_RED_WRED_DROPPED_PACKETS",
	67:  "SAI_PORT_STAT_RED_WRED_DROPPED_BYTES",
	68:  "SAI_PORT_STAT_WRED_DROPPED_PACKETS",
	69:  "SAI_PORT_STAT_WRED_DROPPED_BYTES",
	70:  "SAI_PORT_STAT_ECN_MARKED_PACKETS",
	71:  "SAI_PORT_STAT_ETHER_IN_PKTS_64_OCTETS",
	72:  "SAI_PORT_STAT_ETHER_IN_PKTS_65_TO_127_OCTETS",
	73:  "SAI_PORT_STAT_ETHER_IN_PKTS_128_TO_255_OCTETS",
	74:  "SAI_PORT_STAT_ETHER_IN_PKTS_256_TO_511_OCTETS",
	75:  "SAI_PORT_STAT_ETHER_IN_PKTS_512_TO_1023_OCTETS",
	76:  "SAI_PORT_STAT_ETHER_IN_PKTS_1024_TO_1518_OCTETS",
	77:  "SAI_PORT_STAT_ETHER_IN_PKTS_1519_TO_2047_OCTETS",
	78:  "SAI_PORT_STAT_ETHER_IN_PKTS_2048_TO_4095_OCTETS",
	79:  "SAI_PORT_STAT_ETHER_IN_PKTS_4096_TO_9216_OCTETS",
	80:  "SAI_PORT_STAT_ETHER_IN_PKTS_9217_TO_16383_OCTETS",
	81:  "SAI_PORT_STAT_ETHER_OUT_PKTS_64_OCTETS",
	82:  "SAI_PORT_STAT_ETHER_OUT_PKTS_65_TO_127_OCTETS",
	83:  "SAI_PORT_STAT_ETHER_OUT_PKTS_128_TO_255_OCTETS",
	84:  "SAI_PORT_STAT_ETHER_OUT_PKTS_256_TO_511_OCTETS",
	85:  "SAI_PORT_STAT_ETHER_OUT_PKTS_512_TO_1023_OCTETS",
	86:  "SAI_PORT_STAT_ETHER_OUT_PKTS_1024_TO_1518_OCTETS",
	87:  "SAI_PORT_STAT_ETHER_OUT_PKTS_1519_TO_2047_OCTETS",
	88:  "SAI_PORT_STAT_ETHER_OUT_PKTS_2048_TO_4095_OCTETS",
	89:  "SAI_PORT_STAT_ETHER_OUT_PKTS_4096_TO_9216_OCTETS",
	90:  "SAI_PORT_STAT_ETHER_OUT_PKTS_9217_TO_16383_OCTETS",
	91:  "SAI_PORT_STAT_IN_CURR_OCCUPANCY_BYTES",
	92:  "SAI_PORT_STAT_IN_WATERMARK_BYTES",
	93:  "SAI_PORT_STAT_IN_SHARED_CURR_OCCUPANCY_BYTES",
	94:  "SAI_PORT_STAT_IN_SHARED_WATERMARK_BYTES",
	95:  "SAI_PORT_STAT_OUT_CURR_OCCUPANCY_BYTES",
	96:  "SAI_PORT_STAT_OUT_WATERMARK_BYTES",
	97:  "SAI_PORT_STAT_OUT_SHARED_CURR_OCCUPANCY_BYTES",
	98:  "SAI_PORT_STAT_OUT_SHARED_WATERMARK_BYTES",
	99:  "SAI_PORT_STAT_IN_DROPPED_PKTS",
	100: "SAI_PORT_STAT_OUT_DROPPED_PKTS",
	101: "SAI_PORT_STAT_PAUSE_RX_PKTS",
	102: "SAI_PORT_STAT_PAUSE_TX_PKTS",
	103: "SAI_PORT_STAT_PFC_0_RX_PKTS",
	104: "SAI_PORT_STAT_PFC_0_TX_PKTS",
	105: "SAI_PORT_STAT_PFC_1_RX_PKTS",
	106: "SAI_PORT_STAT_PFC_1_TX_PKTS",
	107: "SAI_PORT_STAT_PFC_2_RX_PKTS",
	108: "SAI_PORT_STAT_PFC_2_TX_PKTS",
	109: "SAI_PORT_STAT_PFC_3_RX_PKTS",
	110: "SAI_PORT_STAT_PFC_3_TX_PKTS",
	111: "SAI_PORT_STAT_PFC_4_RX_PKTS",
	112: "SAI_PORT_STAT_PFC_4_TX_PKTS",
	113: "SAI_PORT_STAT_PFC_5_RX_PKTS",
	114: "SAI_PORT_STAT_PFC_5_TX_PKTS",
	115: "SAI_PORT_STAT_PFC_6_RX_PKTS",
	116: "SAI_PORT_STAT_PFC_6_TX_PKTS",
	117: "SAI_PORT_STAT_PFC_7_RX_PKTS",
	118: "SAI_PORT_STAT_PFC_7_TX_PKTS",
	119: "SAI_PORT_STAT_PFC_0_RX_PAUSE_DURATION",
	120: "SAI_PORT_STAT_PFC_0_TX_PAUSE_DURATION",
	121: "SAI_PORT_STAT_PFC_1_RX_PAUSE_DURATION",
	122: "SAI_PORT_STAT_PFC_1_TX_PAUSE_DURATION",
	123: "SAI_PORT_STAT_PFC_2_RX_PAUSE_DURATION",
	124: "SAI_PORT_STAT_PFC_2_TX_PAUSE_DURATION",
	125: "SAI_PORT_STAT_PFC_3_RX_PAUSE_DURATION",
	126: "SAI_PORT_STAT_PFC_3_TX_PAUSE_DURATION",
	127: "SAI_PORT_STAT_PFC_4_RX_PAUSE_DURATION",
	128: "SAI_PORT_STAT_PFC_4_TX_PAUSE_DURATION",
	129: "SAI_PORT_STAT_PFC_5_RX_PAUSE_DURATION",
	130: "SAI_PORT_STAT_PFC_5_TX_PAUSE_DURATION",
	131: "SAI_PORT_STAT_PFC_6_RX_PAUSE_DURATION",
	132: "SAI_PORT_STAT_PFC_6_TX_PAUSE_DURATION",
	133: "SAI_PORT_STAT_PFC_7_RX_PAUSE_DURATION",
	134: "SAI_PORT_STAT_PFC_7_TX_PAUSE_DURATION",
	135: "SAI_PORT_STAT_PFC_0_ON2OFF_RX_PKTS",
	136: "SAI_PORT_STAT_PFC_1_ON2OFF_RX_PKTS",
	137: "SAI_PORT_STAT_PFC_2_ON2OFF_RX_PKTS",
	138: "SAI_PORT_STAT_PFC_3_ON2OFF_RX_PKTS",
	139: "SAI_PORT_STAT_PFC_4_ON2OFF_RX_PKTS",
	140: "SAI_PORT_STAT_PFC_5_ON2OFF_RX_PKTS",
	141: "SAI_PORT_STAT_PFC_6_ON2OFF_RX_PKTS",
	142: "SAI_PORT_STAT_PFC_7_ON2OFF_RX_PKTS",
	143: "SAI_PORT_STAT_EEE_TX_EVENT_COUNT",
	144: "SAI_PORT_STAT_EEE_RX_EVENT_COUNT",
	145: "SAI_PORT_STAT_EEE_TX_DURATION",
	146: "SAI_PORT_STAT_EEE_RX_DURATION",
}
var SaiPortStatT_value = map[string]int32{
	"SAI_PORT_STAT_IF_IN_OCTETS":                          0,
	"SAI_PORT_STAT_IF_IN_UCAST_PKTS":                      1,
	"SAI_PORT_STAT_IF_IN_NON_UCAST_PKTS":                  2,
	"SAI_PORT_STAT_IF_IN_DISCARDS":                        3,
	"SAI_PORT_STAT_IF_IN_ERRORS":                          4,
	"SAI_PORT_STAT_IF_IN_UNKNOWN_PROTOS":                  5,
	"SAI_PORT_STAT_IF_IN_BROADCAST_PKTS":                  6,
	"SAI_PORT_STAT_IF_IN_MULTICAST_PKTS":                  7,
	"SAI_PORT_STAT_IF_IN_VLAN_DISCARDS":                   8,
	"SAI_PORT_STAT_IF_OUT_OCTETS":                         9,
	"SAI_PORT_STAT_IF_OUT_UCAST_PKTS":                     10,
	"SAI_PORT_STAT_IF_OUT_NON_UCAST_PKTS":                 11,
	"SAI_PORT_STAT_IF_OUT_DISCARDS":                       12,
	"SAI_PORT_STAT_IF_OUT_ERRORS":                         13,
	"SAI_PORT_STAT_IF_OUT_QLEN":                           14,
	"SAI_PORT_STAT_IF_OUT_BROADCAST_PKTS":                 15,
	"SAI_PORT_STAT_IF_OUT_MULTICAST_PKTS":                 16,
	"SAI_PORT_STAT_ETHER_STATS_DROP_EVENTS":               17,
	"SAI_PORT_STAT_ETHER_STATS_MULTICAST_PKTS":            18,
	"SAI_PORT_STAT_ETHER_STATS_BROADCAST_PKTS":            19,
	"SAI_PORT_STAT_ETHER_STATS_UNDERSIZE_PKTS":            20,
	"SAI_PORT_STAT_ETHER_STATS_FRAGMENTS":                 21,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_64_OCTETS":            22,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_65_TO_127_OCTETS":     23,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_128_TO_255_OCTETS":    24,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_256_TO_511_OCTETS":    25,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_512_TO_1023_OCTETS":   26,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_1024_TO_1518_OCTETS":  27,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_1519_TO_2047_OCTETS":  28,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_2048_TO_4095_OCTETS":  29,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_4096_TO_9216_OCTETS":  30,
	"SAI_PORT_STAT_ETHER_STATS_PKTS_9217_TO_16383_OCTETS": 31,
	"SAI_PORT_STAT_ETHER_STATS_OVERSIZE_PKTS":             32,
	"SAI_PORT_STAT_ETHER_RX_OVERSIZE_PKTS":                33,
	"SAI_PORT_STAT_ETHER_TX_OVERSIZE_PKTS":                34,
	"SAI_PORT_STAT_ETHER_STATS_JABBERS":                   35,
	"SAI_PORT_STAT_ETHER_STATS_OCTETS":                    36,
	"SAI_PORT_STAT_ETHER_STATS_PKTS":                      37,
	"SAI_PORT_STAT_ETHER_STATS_COLLISIONS":                38,
	"SAI_PORT_STAT_ETHER_STATS_CRC_ALIGN_ERRORS":          39,
	"SAI_PORT_STAT_ETHER_STATS_TX_NO_ERRORS":              40,
	"SAI_PORT_STAT_ETHER_STATS_RX_NO_ERRORS":              41,
	"SAI_PORT_STAT_IP_IN_RECEIVES":                        42,
	"SAI_PORT_STAT_IP_IN_OCTETS":                          43,
	"SAI_PORT_STAT_IP_IN_UCAST_PKTS":                      44,
	"SAI_PORT_STAT_IP_IN_NON_UCAST_PKTS":                  45,
	"SAI_PORT_STAT_IP_IN_DISCARDS":                        46,
	"SAI_PORT_STAT_IP_OUT_OCTETS":                         47,
	"SAI_PORT_STAT_IP_OUT_UCAST_PKTS":                     48,
	"SAI_PORT_STAT_IP_OUT_NON_UCAST_PKTS":                 49,
	"SAI_PORT_STAT_IP_OUT_DISCARDS":                       50,
	"SAI_PORT_STAT_IPV6_IN_RECEIVES":                      51,
	"SAI_PORT_STAT_IPV6_IN_OCTETS":                        52,
	"SAI_PORT_STAT_IPV6_IN_UCAST_PKTS":                    53,
	"SAI_PORT_STAT_IPV6_IN_NON_UCAST_PKTS":                54,
	"SAI_PORT_STAT_IPV6_IN_MCAST_PKTS":                    55,
	"SAI_PORT_STAT_IPV6_IN_DISCARDS":                      56,
	"SAI_PORT_STAT_IPV6_OUT_OCTETS":                       57,
	"SAI_PORT_STAT_IPV6_OUT_UCAST_PKTS":                   58,
	"SAI_PORT_STAT_IPV6_OUT_NON_UCAST_PKTS":               59,
	"SAI_PORT_STAT_IPV6_OUT_MCAST_PKTS":                   60,
	"SAI_PORT_STAT_IPV6_OUT_DISCARDS":                     61,
	"SAI_PORT_STAT_GREEN_WRED_DROPPED_PACKETS":            62,
	"SAI_PORT_STAT_GREEN_WRED_DROPPED_BYTES":              63,
	"SAI_PORT_STAT_YELLOW_WRED_DROPPED_PACKETS":           64,
	"SAI_PORT_STAT_YELLOW_WRED_DROPPED_BYTES":             65,
	"SAI_PORT_STAT_RED_WRED_DROPPED_PACKETS":              66,
	"SAI_PORT_STAT_RED_WRED_DROPPED_BYTES":                67,
	"SAI_PORT_STAT_WRED_DROPPED_PACKETS":                  68,
	"SAI_PORT_STAT_WRED_DROPPED_BYTES":                    69,
	"SAI_PORT_STAT_ECN_MARKED_PACKETS":                    70,
	"SAI_PORT_STAT_ETHER_IN_PKTS_64_OCTETS":               71,
	"SAI_PORT_STAT_ETHER_IN_PKTS_65_TO_127_OCTETS":        72,
	"SAI_PORT_STAT_ETHER_IN_PKTS_128_TO_255_OCTETS":       73,
	"SAI_PORT_STAT_ETHER_IN_PKTS_256_TO_511_OCTETS":       74,
	"SAI_PORT_STAT_ETHER_IN_PKTS_512_TO_1023_OCTETS":      75,
	"SAI_PORT_STAT_ETHER_IN_PKTS_1024_TO_1518_OCTETS":     76,
	"SAI_PORT_STAT_ETHER_IN_PKTS_1519_TO_2047_OCTETS":     77,
	"SAI_PORT_STAT_ETHER_IN_PKTS_2048_TO_4095_OCTETS":     78,
	"SAI_PORT_STAT_ETHER_IN_PKTS_4096_TO_9216_OCTETS":     79,
	"SAI_PORT_STAT_ETHER_IN_PKTS_9217_TO_16383_OCTETS":    80,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_64_OCTETS":              81,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_65_TO_127_OCTETS":       82,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_128_TO_255_OCTETS":      83,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_256_TO_511_OCTETS":      84,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_512_TO_1023_OCTETS":     85,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_1024_TO_1518_OCTETS":    86,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_1519_TO_2047_OCTETS":    87,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_2048_TO_4095_OCTETS":    88,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_4096_TO_9216_OCTETS":    89,
	"SAI_PORT_STAT_ETHER_OUT_PKTS_9217_TO_16383_OCTETS":   90,
	"SAI_PORT_STAT_IN_CURR_OCCUPANCY_BYTES":               91,
	"SAI_PORT_STAT_IN_WATERMARK_BYTES":                    92,
	"SAI_PORT_STAT_IN_SHARED_CURR_OCCUPANCY_BYTES":        93,
	"SAI_PORT_STAT_IN_SHARED_WATERMARK_BYTES":             94,
	"SAI_PORT_STAT_OUT_CURR_OCCUPANCY_BYTES":              95,
	"SAI_PORT_STAT_OUT_WATERMARK_BYTES":                   96,
	"SAI_PORT_STAT_OUT_SHARED_CURR_OCCUPANCY_BYTES":       97,
	"SAI_PORT_STAT_OUT_SHARED_WATERMARK_BYTES":            98,
	"SAI_PORT_STAT_IN_DROPPED_PKTS":                       99,
	"SAI_PORT_STAT_OUT_DROPPED_PKTS":                      100,
	"SAI_PORT_STAT_PAUSE_RX_PKTS":                         101,
	"SAI_PORT_STAT_PAUSE_TX_PKTS":                         102,
	"SAI_PORT_STAT_PFC_0_RX_PKTS":                         103,
	"SAI_PORT_STAT_PFC_0_TX_PKTS":                         104,
	"SAI_PORT_STAT_PFC_1_RX_PKTS":                         105,
	"SAI_PORT_STAT_PFC_1_TX_PKTS":                         106,
	"SAI_PORT_STAT_PFC_2_RX_PKTS":                         107,
	"SAI_PORT_STAT_PFC_2_TX_PKTS":                         108,
	"SAI_PORT_STAT_PFC_3_RX_PKTS":                         109,
	"SAI_PORT_STAT_PFC_3_TX_PKTS":                         110,
	"SAI_PORT_STAT_PFC_4_RX_PKTS":                         111,
	"SAI_PORT_STAT_PFC_4_TX_PKTS":                         112,
	"SAI_PORT_STAT_PFC_5_RX_PKTS":                         113,
	"SAI_PORT_STAT_PFC_5_TX_PKTS":                         114,
	"SAI_PORT_STAT_PFC_6_RX_PKTS":                         115,
	"SAI_PORT_STAT_PFC_6_TX_PKTS":                         116,
	"SAI_PORT_STAT_PFC_7_RX_PKTS":                         117,
	"SAI_PORT_STAT_PFC_7_TX_PKTS":                         118,
	"SAI_PORT_STAT_PFC_0_RX_PAUSE_DURATION":               119,
	"SAI_PORT_STAT_PFC_0_TX_PAUSE_DURATION":               120,
	"SAI_PORT_STAT_PFC_1_RX_PAUSE_DURATION":               121,
	"SAI_PORT_STAT_PFC_1_TX_PAUSE_DURATION":               122,
	"SAI_PORT_STAT_PFC_2_RX_PAUSE_DURATION":               123,
	"SAI_PORT_STAT_PFC_2_TX_PAUSE_DURATION":               124,
	"SAI_PORT_STAT_PFC_3_RX_PAUSE_DURATION":               125,
	"SAI_PORT_STAT_PFC_3_TX_PAUSE_DURATION":               126,
	"SAI_PORT_STAT_PFC_4_RX_PAUSE_DURATION":               127,
	"SAI_PORT_STAT_PFC_4_TX_PAUSE_DURATION":               128,
	"SAI_PORT_STAT_PFC_5_RX_PAUSE_DURATION":               129,
	"SAI_PORT_STAT_PFC_5_TX_PAUSE_DURATION":               130,
	"SAI_PORT_STAT_PFC_6_RX_PAUSE_DURATION":               131,
	"SAI_PORT_STAT_PFC_6_TX_PAUSE_DURATION":               132,
	"SAI_PORT_STAT_PFC_7_RX_PAUSE_DURATION":               133,
	"SAI_PORT_STAT_PFC_7_TX_PAUSE_DURATION":               134,
	"SAI_PORT_STAT_PFC_0_ON2OFF_RX_PKTS":                  135,
	"SAI_PORT_STAT_PFC_1_ON2OFF_RX_PKTS":                  136,
	"SAI_PORT_STAT_PFC_2_ON2OFF_RX_PKTS":                  137,
	"SAI_PORT_STAT_PFC_3_ON2OFF_RX_PKTS":                  138,
	"SAI_PORT_STAT_PFC_4_ON2OFF_RX_PKTS":                  139,
	"SAI_PORT_STAT_PFC_5_ON2OFF_RX_PKTS":                  140,
	"SAI_PORT_STAT_PFC_6_ON2OFF_RX_PKTS":                  141,
	"SAI_PORT_STAT_PFC_7_ON2OFF_RX_PKTS":                  142,
	"SAI_PORT_STAT_EEE_TX_EVENT_COUNT":                    143,
	"SAI_PORT_STAT_EEE_RX_EVENT_COUNT":                    144,
	"SAI_PORT_STAT_EEE_TX_DURATION":                       145,
	"SAI_PORT_STAT_EEE_RX_DURATION":                       146,
}

func (x SaiPortStatT) String() string {
	return proto.EnumName(SaiPortStatT_name, int32(x))
}
func (SaiPortStatT) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterEnum("gnmi.sonic.CountersTableT", CountersTableT_name, CountersTableT_value)
	proto.RegisterEnum("gnmi.sonic.SaiPortStatT", SaiPortStatT_name, SaiPortStatT_value)
}

func init() { proto.RegisterFile("port_stat.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x99, 0x79, 0x5b, 0xdb, 0xc6,
	0x16, 0xc6, 0xe3, 0x6c, 0x37, 0x77, 0x6e, 0xee, 0x8d, 0xee, 0xb4, 0xcd, 0x42, 0x76, 0x12, 0x42,
	0x42, 0x12, 0xb0, 0x64, 0xcb, 0x86, 0xee, 0x42, 0x1e, 0x88, 0x82, 0x2d, 0x29, 0x23, 0xc9, 0x40,
	0xba, 0x4c, 0x81, 0x12, 0x42, 0x9b, 0x60, 0x0a, 0x4e, 0xf7, 0x7d, 0xdf, 0xb7, 0xcf, 0xd0, 0x2f,
	0xd0, 0x6f, 0xd8, 0x47, 0xb2, 0x25, 0x8b, 0x99, 0x73, 0x2c, 0xfe, 0x23, 0x8f, 0x7e, 0xef, 0xeb,
	0x33, 0xc7, 0x47, 0xf3, 0x9e, 0x00, 0x39, 0xb1, 0xdd, 0xd9, 0xe9, 0x8a, 0xdd, 0xee, 0x4a, 0x77,
	0x72, 0x7b, 0xa7, 0xd3, 0xed, 0x50, 0xb2, 0xb1, 0xf5, 0x78, 0x73, 0x72, 0xb7, 0xb3, 0xb5, 0xb9,
	0x36, 0x52, 0xde, 0xd8, 0xec, 0x3e, 0x7c, 0xb2, 0x3a, 0xb9, 0xd6, 0x79, 0x3c, 0xd5, 0xd9, 0x5e,
	0xdf, 0x5a, 0xeb, 0x6c, 0x3d, 0xd8, 0xdc, 0x98, 0x8a, 0x89, 0xa9, 0x84, 0xee, 0xfd, 0x98, 0x28,
	0x92, 0x7f, 0x4f, 0xfc, 0x5d, 0x22, 0xda, 0x5a, 0xe7, 0xc9, 0x56, 0x77, 0x7d, 0x67, 0x57, 0x74,
	0x57, 0x56, 0x1f, 0xad, 0x8b, 0x2e, 0x1d, 0x21, 0x27, 0x6d, 0x2f, 0x72, 0x43, 0xc6, 0x03, 0xe1,
	0x7b, 0x3c, 0x14, 0xae, 0xd5, 0x62, 0xa2, 0x65, 0xf9, 0xda, 0x01, 0x7a, 0x9c, 0x1c, 0x4b, 0x9f,
	0x69, 0x25, 0x7a, 0x96, 0x9c, 0xca, 0xc8, 0x7b, 0x11, 0x8b, 0xd8, 0x00, 0x3d, 0x08, 0x3c, 0x4c,
	0xcc, 0xe2, 0x87, 0x87, 0xe8, 0x39, 0x72, 0x5a, 0x7a, 0xe8, 0xb8, 0x0d, 0xb6, 0x94, 0x3c, 0x3d,
	0x0c, 0x48, 0xc3, 0x65, 0xbf, 0xe7, 0x7b, 0x64, 0xe2, 0xaf, 0x32, 0x39, 0xb1, 0xbb, 0xb2, 0x29,
	0xb2, 0x4e, 0x88, 0x2e, 0xbd, 0x40, 0x46, 0x02, 0xcb, 0xe9, 0x7d, 0x40, 0x10, 0x5a, 0xa1, 0x70,
	0xe6, 0x84, 0xe3, 0x0a, 0xcf, 0x0e, 0x59, 0x18, 0x68, 0x07, 0xe8, 0x28, 0xb9, 0x00, 0x3d, 0x8f,
	0x6c, 0x2b, 0x08, 0x85, 0xbf, 0x10, 0xc6, 0x87, 0xb9, 0x46, 0x46, 0x21, 0xc6, 0xf5, 0xf6, 0x70,
	0x07, 0xe9, 0x25, 0x72, 0x0e, 0xe2, 0x1a, 0x4e, 0x60, 0x5b, 0xbc, 0x11, 0x68, 0x87, 0xb0, 0x6a,
	0x18, 0xe7, 0x1e, 0x0f, 0xb4, 0xc3, 0xd8, 0x27, 0x45, 0xee, 0x82, 0xeb, 0x2d, 0xba, 0xc2, 0xe7,
	0x5e, 0xe8, 0x05, 0xda, 0x11, 0x8c, 0x9b, 0xe5, 0x9e, 0xd5, 0x18, 0x54, 0x74, 0x14, 0xe3, 0x5a,
	0x51, 0x33, 0x74, 0x06, 0xdc, 0xbf, 0xe8, 0x18, 0xb9, 0x0c, 0x71, 0xed, 0xa6, 0x95, 0x2b, 0xff,
	0x18, 0xbd, 0x48, 0xce, 0x2a, 0x98, 0x17, 0x85, 0x69, 0x37, 0xff, 0x4d, 0xaf, 0x90, 0x8b, 0x20,
	0x90, 0x6b, 0x13, 0xa1, 0xe3, 0xe4, 0x0a, 0x08, 0x49, 0xfd, 0xfc, 0x0f, 0xbd, 0x4c, 0xce, 0x83,
	0x60, 0x56, 0xd1, 0x71, 0xb4, 0xa2, 0x7e, 0x47, 0xff, 0x4b, 0xcf, 0x93, 0x33, 0x20, 0x70, 0xaf,
	0xc9, 0x5c, 0xed, 0x7f, 0x68, 0x2d, 0x52, 0x27, 0x4f, 0xa0, 0xa0, 0xd4, 0x4a, 0x8d, 0xde, 0x20,
	0x63, 0x7b, 0x41, 0x16, 0xde, 0x61, 0x3c, 0xf9, 0x31, 0x10, 0x0d, 0xee, 0xf9, 0x82, 0xb5, 0x99,
	0x1b, 0x06, 0xda, 0xff, 0xe9, 0x2d, 0x72, 0x1d, 0x47, 0x25, 0x63, 0x3a, 0x9c, 0x96, 0xea, 0x7d,
	0x6a, 0x38, 0x1d, 0xb9, 0x0d, 0xc6, 0x03, 0xe7, 0x3e, 0xeb, 0xd1, 0x4f, 0xab, 0xa7, 0xcb, 0xd3,
	0x73, 0xdc, 0x9a, 0x6f, 0x25, 0x25, 0x3f, 0x33, 0xdc, 0x36, 0x36, 0x13, 0xb5, 0x6a, 0x3a, 0x0e,
	0x27, 0x69, 0x85, 0x4c, 0x15, 0xd1, 0xa6, 0x08, 0x3d, 0xa1, 0x1b, 0xf5, 0x54, 0x74, 0x8a, 0x56,
	0x49, 0xb9, 0x40, 0xa4, 0x1b, 0xd3, 0xb1, 0xca, 0x30, 0xcd, 0x54, 0x75, 0x7a, 0x1f, 0x2a, 0xc3,
	0xac, 0xc5, 0x2a, 0x53, 0xd7, 0x53, 0xd5, 0x19, 0x6a, 0x12, 0xbd, 0x40, 0x65, 0xea, 0x46, 0x52,
	0x61, 0xd9, 0xa8, 0xa4, 0xb2, 0x11, 0x5a, 0x23, 0x46, 0x51, 0x89, 0x65, 0xa3, 0x9a, 0xe8, 0x4c,
	0x7d, 0x3a, 0xd5, 0x9d, 0xdd, 0x8f, 0xce, 0xd4, 0x67, 0x92, 0xb3, 0x95, 0xab, 0x59, 0x4b, 0xce,
	0xed, 0x43, 0x67, 0x94, 0xab, 0x49, 0x4f, 0xaa, 0xe5, 0x99, 0xac, 0x29, 0xe7, 0xf7, 0xa1, 0xab,
	0x96, 0x67, 0x92, 0xae, 0xcc, 0x18, 0x7a, 0x2d, 0xd5, 0x5d, 0xa0, 0x75, 0x52, 0x29, 0xd0, 0xcd,
	0x18, 0x7a, 0x3d, 0x39, 0x5f, 0xad, 0x32, 0x9d, 0x35, 0xe6, 0x22, 0xbd, 0x49, 0xc6, 0x71, 0xa1,
	0xd7, 0xce, 0x0f, 0xdd, 0x25, 0x7a, 0x9d, 0x5c, 0x85, 0x60, 0xbe, 0x24, 0x91, 0x97, 0x31, 0x32,
	0x94, 0xc9, 0x51, 0xf5, 0x22, 0xcb, 0x17, 0x70, 0xd7, 0x9a, 0x9d, 0x8d, 0xe3, 0xe9, 0x0a, 0xbd,
	0x4a, 0x2e, 0x0d, 0xa9, 0xb3, 0x77, 0x9a, 0xab, 0x6a, 0x36, 0xc8, 0x6d, 0xd0, 0xc6, 0xb0, 0xd2,
	0x7a, 0x8c, 0xed, 0x35, 0x9b, 0x4e, 0xe0, 0x78, 0x6e, 0xa0, 0x5d, 0xa3, 0x93, 0x64, 0x62, 0x08,
	0xc9, 0x6d, 0x61, 0x35, 0x9d, 0xf9, 0x2c, 0x0b, 0xc6, 0xe9, 0x04, 0xb9, 0x86, 0xf3, 0xe1, 0x92,
	0x70, 0xbd, 0x94, 0xbd, 0x3e, 0x9c, 0xe5, 0x79, 0xf6, 0x06, 0x90, 0x52, 0x7e, 0x7c, 0xd7, 0x73,
	0x66, 0x33, 0xa7, 0xcd, 0x02, 0x6d, 0x02, 0x48, 0x29, 0x3f, 0x97, 0x99, 0x37, 0x81, 0xcc, 0xf4,
	0xa5, 0xcc, 0xbc, 0x05, 0x24, 0x8f, 0x0f, 0x64, 0xe6, 0x6d, 0xac, 0x9a, 0xec, 0x8a, 0x9f, 0x04,
	0xae, 0x78, 0x3f, 0x1f, 0x3a, 0x53, 0x40, 0xe8, 0xf8, 0x72, 0xe8, 0x94, 0x81, 0xfb, 0xdb, 0x87,
	0x42, 0x47, 0x07, 0x42, 0xc7, 0xdf, 0x1b, 0x3a, 0x06, 0x74, 0xfe, 0x76, 0x6d, 0x4f, 0x0f, 0x2b,
	0xd0, 0xb9, 0x7a, 0x4c, 0xbf, 0xec, 0xaa, 0x3a, 0x83, 0x29, 0x91, 0x2b, 0xc7, 0x54, 0xe7, 0x2b,
	0xa5, 0xa4, 0xc2, 0x6b, 0xb8, 0x5f, 0x6b, 0x40, 0xd5, 0xf1, 0xda, 0xb3, 0xf3, 0x4d, 0x43, 0x2d,
	0x68, 0xd7, 0xf2, 0x3d, 0x9f, 0x01, 0x16, 0x86, 0x14, 0xc9, 0xd5, 0xf4, 0xac, 0x1a, 0x86, 0x19,
	0x26, 0x95, 0xff, 0xdc, 0x10, 0xc7, 0x5c, 0xfd, 0xcf, 0x43, 0x5f, 0x76, 0x1f, 0xcb, 0x0e, 0xf0,
	0x82, 0x9a, 0x52, 0xf3, 0x9c, 0x31, 0x57, 0x2c, 0x72, 0xd6, 0x48, 0x22, 0xd8, 0x67, 0x0d, 0xe1,
	0x5b, 0xf6, 0x42, 0x7c, 0x96, 0x17, 0xd5, 0x97, 0x07, 0xa0, 0x67, 0x97, 0x43, 0x16, 0x68, 0x2f,
	0xd1, 0xdb, 0xe4, 0xc6, 0x5e, 0x76, 0x99, 0x35, 0x9b, 0xde, 0x22, 0x6c, 0xfd, 0xb2, 0x7a, 0x1f,
	0x42, 0x78, 0xcf, 0xdb, 0x52, 0xeb, 0x88, 0x21, 0xd0, 0x78, 0x56, 0x1d, 0x0b, 0x85, 0xed, 0xb9,
	0xda, 0xea, 0x8b, 0x08, 0x3a, 0x36, 0xd4, 0xf1, 0x01, 0xdc, 0x18, 0x70, 0x71, 0xda, 0xae, 0x68,
	0x59, 0x7c, 0x21, 0xe7, 0x35, 0x87, 0xed, 0x40, 0x8e, 0x2b, 0xaf, 0x08, 0xf3, 0xb4, 0x4c, 0x6e,
	0x0d, 0x45, 0xe5, 0xfd, 0xe0, 0x0e, 0xd5, 0xc9, 0xed, 0x61, 0x0a, 0x75, 0x39, 0x70, 0x8a, 0x24,
	0xea, 0x66, 0x70, 0x97, 0x1a, 0x64, 0x72, 0x98, 0x04, 0x58, 0x0b, 0x16, 0xb0, 0x75, 0x27, 0xab,
	0x0c, 0xd8, 0x09, 0x9a, 0x85, 0x22, 0x60, 0x21, 0x68, 0x15, 0x89, 0xa0, 0x6d, 0xc0, 0x2d, 0x12,
	0x41, 0xab, 0x80, 0x87, 0xed, 0x55, 0xa9, 0x08, 0xdc, 0x03, 0x7c, 0x2c, 0x8f, 0xe2, 0xd7, 0x54,
	0x9a, 0x80, 0x7b, 0xd8, 0x97, 0x33, 0x60, 0xe5, 0x11, 0xe0, 0xd8, 0x97, 0x93, 0x49, 0xd4, 0x19,
	0x08, 0x0a, 0x35, 0xea, 0x10, 0x84, 0x58, 0xc7, 0x32, 0x0d, 0x30, 0x05, 0x11, 0xd6, 0xb1, 0x41,
	0x71, 0xc0, 0x18, 0xb4, 0x8b, 0x55, 0xc0, 0x1c, 0x2c, 0x16, 0xaa, 0xa0, 0x41, 0x58, 0x2a, 0x54,
	0x41, 0x93, 0xb0, 0x8c, 0xed, 0xca, 0x99, 0x0a, 0x1c, 0x85, 0xfb, 0x40, 0x04, 0xb8, 0xc2, 0x8e,
	0x38, 0x17, 0x9e, 0x6d, 0x47, 0xbe, 0xe5, 0xda, 0xcb, 0xfd, 0xcb, 0xe5, 0x15, 0x20, 0xc1, 0x5c,
	0xb1, 0x68, 0x85, 0x8c, 0xc7, 0x17, 0x4c, 0x9f, 0x7a, 0x55, 0xbd, 0x31, 0x1c, 0x57, 0x04, 0x77,
	0xac, 0xf8, 0xb6, 0x02, 0x7d, 0x5f, 0x53, 0x6f, 0xe1, 0x81, 0x42, 0xb6, 0x7f, 0x5d, 0x1d, 0xdd,
	0xf8, 0x80, 0xa0, 0xb1, 0x50, 0x33, 0x2b, 0x66, 0x65, 0xcb, 0x37, 0xd4, 0x09, 0x8f, 0xb1, 0x61,
	0x25, 0xaf, 0xa8, 0x09, 0x96, 0x93, 0xc8, 0x1f, 0xb0, 0x0a, 0x04, 0xb6, 0x3b, 0xb8, 0xe1, 0xe3,
	0xdc, 0x5c, 0x53, 0x73, 0x3f, 0x89, 0xcc, 0x3c, 0xf3, 0xa6, 0xba, 0x69, 0xf9, 0x56, 0x14, 0xb0,
	0x78, 0x7f, 0x4c, 0x80, 0x75, 0x0c, 0x08, 0xfb, 0xc0, 0x03, 0x00, 0x98, 0xb3, 0x45, 0x39, 0x73,
	0xd8, 0xc0, 0x80, 0xd4, 0xe1, 0x21, 0x0c, 0xe8, 0x99, 0xc3, 0x26, 0x06, 0xa4, 0x0e, 0x6f, 0xc1,
	0x80, 0x91, 0x39, 0xbc, 0x8d, 0x01, 0xa9, 0xc3, 0x23, 0x18, 0xa8, 0x64, 0x0e, 0x8f, 0x31, 0x20,
	0x75, 0xd8, 0x82, 0x81, 0x6a, 0xe6, 0xd0, 0xc1, 0x80, 0xd4, 0x61, 0x1b, 0x06, 0xcc, 0xcc, 0xe1,
	0x1d, 0x0c, 0x48, 0x1d, 0x76, 0x60, 0xa0, 0x96, 0x39, 0xec, 0x62, 0x40, 0xea, 0xd0, 0x85, 0x81,
	0x7a, 0xe6, 0xf0, 0x04, 0x03, 0x52, 0x87, 0x77, 0xd5, 0x97, 0x7f, 0x30, 0x0f, 0xc9, 0xe4, 0x34,
	0x22, 0x6e, 0x85, 0x8e, 0xe7, 0x6a, 0xef, 0x61, 0x68, 0xa8, 0xa0, 0xef, 0xc3, 0xa8, 0x0e, 0xb8,
	0x7e, 0x80, 0xa1, 0xaa, 0xeb, 0x87, 0x30, 0x6a, 0x00, 0xae, 0x1f, 0x61, 0xa8, 0xea, 0xfa, 0x31,
	0x8c, 0x56, 0x00, 0xd7, 0x4f, 0x30, 0x54, 0x75, 0xfd, 0x14, 0x46, 0xab, 0x80, 0xeb, 0x67, 0x74,
	0x02, 0x46, 0x55, 0xd7, 0xcf, 0x4b, 0x30, 0x6b, 0x02, 0xb6, 0x5f, 0xa0, 0xac, 0xea, 0xfb, 0x25,
	0xc2, 0xd6, 0x00, 0xdf, 0xaf, 0x50, 0x56, 0xf5, 0xfd, 0x1a, 0x61, 0xeb, 0x80, 0xef, 0x37, 0x28,
	0xab, 0xfa, 0x7e, 0x5b, 0xa2, 0xe3, 0xf2, 0xce, 0xdc, 0x9b, 0x45, 0xcf, 0x35, 0xbc, 0xb9, 0xb9,
	0x6c, 0xfe, 0xbf, 0x43, 0x40, 0x5d, 0x06, 0xbf, 0x47, 0x40, 0x43, 0x06, 0x7f, 0x40, 0xc0, 0x8a,
	0x0c, 0xfe, 0x88, 0x80, 0x55, 0x19, 0xfc, 0x09, 0x01, 0x4d, 0x19, 0xfc, 0x19, 0x01, 0x6b, 0x32,
	0xf8, 0x0b, 0x02, 0xd6, 0x65, 0xf0, 0xd7, 0x12, 0x1d, 0x53, 0xfe, 0xb7, 0xc0, 0x92, 0xb4, 0x48,
	0x7e, 0x03, 0x2a, 0x92, 0x5f, 0xe4, 0x6b, 0xbf, 0x21, 0x18, 0xdf, 0x8b, 0xfd, 0x5e, 0xa2, 0xa3,
	0x72, 0xca, 0xf5, 0xdd, 0xb2, 0x6f, 0xee, 0x0f, 0x84, 0xe1, 0x39, 0xe6, 0xcf, 0xd2, 0xea, 0xd1,
	0xe4, 0x2f, 0x1c, 0x95, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x89, 0x0e, 0xf2, 0x34, 0x32, 0x19,
	0x00, 0x00,
}
