// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sonic.proto

package gnmi_sonic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/openconfig/gnmi/proto/gnmi"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// target - the name of the target for which the path is a member. Only set in prefix for a path.
type Target int32

const (
	Target_APPL_DB     Target = 0
	Target_ASIC_DB     Target = 1
	Target_COUNTERS_DB Target = 2
	Target_CONFIG_DB   Target = 4
	// PFC_WD_DB shares the the same db number with FLEX_COUNTER_DB
	Target_PFC_WD_DB       Target = 5
	Target_FLEX_COUNTER_DB Target = 5
	Target_STATE_DB        Target = 6
	Target_BMP_STATE_DB    Target = 20
	// For none-DB data
	Target_OTHERS Target = 100
)

var Target_name = map[int32]string{
	0: "APPL_DB",
	1: "ASIC_DB",
	2: "COUNTERS_DB",
	4: "CONFIG_DB",
	5: "PFC_WD_DB",
	// Duplicate value: 5: "FLEX_COUNTER_DB",
	6:   "STATE_DB",
	20:  "BMP_STATE_DB",
	100: "OTHERS",
}

var Target_value = map[string]int32{
	"APPL_DB":         0,
	"ASIC_DB":         1,
	"COUNTERS_DB":     2,
	"CONFIG_DB":       4,
	"PFC_WD_DB":       5,
	"FLEX_COUNTER_DB": 5,
	"STATE_DB":        6,
	"BMP_STATE_DB":    20,
	"OTHERS":          100,
}

func (x Target) String() string {
	return proto.EnumName(Target_name, int32(x))
}

func (Target) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d8b4eb81a68e9be, []int{0}
}

type SupportedBundleVersions struct {
	BundleVersion        string   `protobuf:"bytes,1,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	BaseVersion          string   `protobuf:"bytes,2,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SupportedBundleVersions) Reset()         { *m = SupportedBundleVersions{} }
func (m *SupportedBundleVersions) String() string { return proto.CompactTextString(m) }
func (*SupportedBundleVersions) ProtoMessage()    {}
func (*SupportedBundleVersions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d8b4eb81a68e9be, []int{0}
}

func (m *SupportedBundleVersions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SupportedBundleVersions.Unmarshal(m, b)
}
func (m *SupportedBundleVersions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SupportedBundleVersions.Marshal(b, m, deterministic)
}
func (m *SupportedBundleVersions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SupportedBundleVersions.Merge(m, src)
}
func (m *SupportedBundleVersions) XXX_Size() int {
	return xxx_messageInfo_SupportedBundleVersions.Size(m)
}
func (m *SupportedBundleVersions) XXX_DiscardUnknown() {
	xxx_messageInfo_SupportedBundleVersions.DiscardUnknown(m)
}

var xxx_messageInfo_SupportedBundleVersions proto.InternalMessageInfo

func (m *SupportedBundleVersions) GetBundleVersion() string {
	if m != nil {
		return m.BundleVersion
	}
	return ""
}

func (m *SupportedBundleVersions) GetBaseVersion() string {
	if m != nil {
		return m.BaseVersion
	}
	return ""
}

type BundleVersion struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BundleVersion) Reset()         { *m = BundleVersion{} }
func (m *BundleVersion) String() string { return proto.CompactTextString(m) }
func (*BundleVersion) ProtoMessage()    {}
func (*BundleVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d8b4eb81a68e9be, []int{1}
}

func (m *BundleVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BundleVersion.Unmarshal(m, b)
}
func (m *BundleVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BundleVersion.Marshal(b, m, deterministic)
}
func (m *BundleVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BundleVersion.Merge(m, src)
}
func (m *BundleVersion) XXX_Size() int {
	return xxx_messageInfo_BundleVersion.Size(m)
}
func (m *BundleVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_BundleVersion.DiscardUnknown(m)
}

var xxx_messageInfo_BundleVersion proto.InternalMessageInfo

func (m *BundleVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterEnum("gnmi.sonic.Target", Target_name, Target_value)
	proto.RegisterType((*SupportedBundleVersions)(nil), "gnmi.sonic.SupportedBundleVersions")
	proto.RegisterType((*BundleVersion)(nil), "gnmi.sonic.BundleVersion")
}

func init() { proto.RegisterFile("sonic.proto", fileDescriptor_2d8b4eb81a68e9be) }

var fileDescriptor_2d8b4eb81a68e9be = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4f, 0x83, 0x30,
	0x18, 0x87, 0x2d, 0x51, 0xe6, 0x5e, 0xc0, 0x91, 0x57, 0x13, 0x97, 0x9d, 0x74, 0x89, 0x89, 0x7a,
	0xd8, 0xc5, 0x4f, 0x30, 0x18, 0xe8, 0x92, 0x39, 0x08, 0xad, 0x7f, 0x6e, 0xcd, 0x18, 0x64, 0x21,
	0x51, 0x4a, 0x5a, 0xe6, 0x47, 0xf1, 0xf3, 0x9a, 0x96, 0xa9, 0xdb, 0xad, 0xcf, 0x93, 0xa7, 0xbf,
	0xc3, 0x0b, 0x8e, 0x12, 0x75, 0xb5, 0x9e, 0x34, 0x52, 0xb4, 0x02, 0x61, 0x53, 0x7f, 0x56, 0x13,
	0x63, 0x46, 0xdd, 0xdb, 0xf8, 0xf1, 0x1a, 0x2e, 0xe9, 0xb6, 0x69, 0x84, 0x6c, 0xcb, 0x22, 0xd8,
	0xd6, 0xc5, 0x47, 0xf9, 0x5a, 0x4a, 0x55, 0x89, 0x5a, 0xe1, 0x0d, 0x9c, 0xe5, 0xc6, 0xf0, 0xaf,
	0x4e, 0x0d, 0xc9, 0x15, 0xb9, 0xed, 0x67, 0x5e, 0xbe, 0xdf, 0xe1, 0x35, 0xb8, 0xf9, 0x4a, 0xfd,
	0x47, 0x96, 0x89, 0x1c, 0xed, 0x76, 0xc9, 0xf8, 0x0e, 0xbc, 0x83, 0x6d, 0x1c, 0x42, 0xef, 0x70,
	0xf3, 0x17, 0xef, 0xbf, 0x09, 0xd8, 0x6c, 0x25, 0x37, 0x65, 0x8b, 0x0e, 0xf4, 0xa6, 0x69, 0xba,
	0xe0, 0xb3, 0xc0, 0x3f, 0x32, 0x40, 0xe7, 0xa1, 0x06, 0x82, 0x03, 0x70, 0xc2, 0xe4, 0x65, 0xc9,
	0xa2, 0x8c, 0x6a, 0x61, 0xa1, 0x07, 0xfd, 0x30, 0x59, 0xc6, 0xf3, 0x47, 0x8d, 0xc7, 0x1a, 0xd3,
	0x38, 0xe4, 0x6f, 0x33, 0x8d, 0x27, 0x78, 0x0e, 0x83, 0x78, 0x11, 0xbd, 0xf3, 0xdd, 0x9f, 0x4e,
	0xba, 0x70, 0x4a, 0xd9, 0x94, 0x45, 0x9a, 0x6c, 0xf4, 0xc1, 0x0d, 0x9e, 0x53, 0xfe, 0x67, 0x2e,
	0x10, 0xc0, 0x4e, 0xd8, 0x53, 0x94, 0x51, 0xbf, 0x18, 0x59, 0x3e, 0xc9, 0x6d, 0x73, 0xaf, 0x87,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x18, 0xec, 0x9b, 0x56, 0x01, 0x00, 0x00,
}
