package gnmi

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"golang.org/x/sys/unix"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const (
	// Healthz reads host artifacts through the read-only mount.
	hostFilesystemMount      string = "/mnt/host"
	legacyArtifactDirectory  string = "/tmp/dump"
	dlddArtifactDirectory    string = "/var/lib/sonic/dldd/artifacts"
	healthzArtifactDirectory string = "/var/lib/sonic/healthz/artifacts"
)

var (
	// Relative IDs expose only archives generated by DLDD or host Healthz.
	opaqueArtifactIDPattern = regexp.MustCompile(`^(dldd|healthz)-[0-9a-f]{32}\.tar\.gz$`)
	defaultArtifactResolver = artifactPathResolver{
		hostMount:        hostFilesystemMount,
		legacyDirectory:  legacyArtifactDirectory,
		dlddDirectory:    dlddArtifactDirectory,
		healthzDirectory: healthzArtifactDirectory,
	}
)

type artifactPathResolver struct {
	hostMount        string
	legacyDirectory  string
	dlddDirectory    string
	healthzDirectory string
}

// openLegacy opens an absolute debug artifact and excludes opaque archive IDs.
func (r artifactPathResolver) openLegacy(artifactID string) (*os.File, string, error) {
	if !filepath.IsAbs(artifactID) {
		return nil, "", status.Error(codes.InvalidArgument, "legacy artifact ID must be an absolute path")
	}
	for _, component := range strings.Split(artifactID, string(filepath.Separator)) {
		if component == ".." {
			return nil, "", status.Error(codes.InvalidArgument, "legacy artifact ID must not contain parent traversal")
		}
	}
	return r.open(artifactID)
}

// open pins every path component beneath the trusted host mount without
// following symbolic links, including ancestors of the artifact directory.
func (r artifactPathResolver) open(artifactID string) (*os.File, string, error) {
	containerPath, err := r.resolve(artifactID)
	if err != nil {
		return nil, "", err
	}

	file, err := openArtifactPath(r.hostMount, containerPath)
	if err != nil {
		return nil, "", err
	}
	return file, containerPath, nil
}

func (r artifactPathResolver) resolve(artifactID string) (string, error) {
	if artifactID == "" || strings.IndexByte(artifactID, 0) >= 0 {
		return "", status.Error(codes.InvalidArgument, "artifact ID is empty or invalid")
	}

	var artifactDirectory string
	var hostPath string
	if filepath.IsAbs(artifactID) {
		artifactDirectory = filepath.Clean(r.legacyDirectory)
		hostPath = filepath.Clean(artifactID)
		if !isPathWithin(artifactDirectory, hostPath) {
			return "", status.Error(codes.InvalidArgument, "legacy artifact path is outside the allowed directory")
		}
	} else {
		if !opaqueArtifactIDPattern.MatchString(artifactID) {
			return "", status.Error(codes.InvalidArgument, "artifact ID contains unsupported characters")
		}
		artifactDirectory = filepath.Clean(r.artifactDirectory(artifactID))
		hostPath = filepath.Join(artifactDirectory, artifactID)
	}

	containerDirectory := r.containerPath(artifactDirectory)
	containerPath := r.containerPath(hostPath)
	if !isPathWithin(containerDirectory, containerPath) {
		return "", status.Error(codes.InvalidArgument, "artifact path is outside the allowed directory")
	}
	return containerPath, nil
}

func (r artifactPathResolver) artifactDirectory(artifactID string) string {
	if filepath.IsAbs(artifactID) {
		return r.legacyDirectory
	}
	if strings.HasPrefix(artifactID, "healthz-") {
		return r.healthzDirectory
	}
	return r.dlddDirectory
}

func (r artifactPathResolver) containerPath(hostPath string) string {
	cleanPath := filepath.Clean(hostPath)
	return filepath.Join(r.hostMount, strings.TrimPrefix(cleanPath, string(filepath.Separator)))
}

func isPathWithin(root, candidate string) bool {
	rel, err := filepath.Rel(root, candidate)
	if err != nil || rel == "." || filepath.IsAbs(rel) {
		return false
	}
	return rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}

func openArtifactPath(mount, candidate string) (*os.File, error) {
	if !isPathWithin(mount, candidate) {
		return nil, status.Error(codes.InvalidArgument, "artifact path is outside the host mount")
	}
	directoryFlags := unix.O_RDONLY | unix.O_DIRECTORY | unix.O_NOFOLLOW | unix.O_CLOEXEC
	directoryFD, err := unix.Open(mount, directoryFlags, 0)
	if err != nil {
		return nil, artifactOpenError(unix.AT_FDCWD, mount, err)
	}
	defer func() { unix.Close(directoryFD) }()

	relativePath, _ := filepath.Rel(mount, candidate)
	parts := strings.Split(relativePath, string(filepath.Separator))
	for _, part := range parts[:len(parts)-1] {
		nextFD, err := unix.Openat(directoryFD, part, directoryFlags, 0)
		if err != nil {
			return nil, artifactOpenError(directoryFD, part, err)
		}
		unix.Close(directoryFD)
		directoryFD = nextFD
	}
	name := parts[len(parts)-1]
	fd, err := unix.Openat(directoryFD, name, unix.O_RDONLY|unix.O_NOFOLLOW|unix.O_NONBLOCK|unix.O_CLOEXEC, 0)
	if err != nil {
		return nil, artifactOpenError(directoryFD, name, err)
	}
	file := os.NewFile(uintptr(fd), candidate)
	info, err := file.Stat()
	if err != nil {
		file.Close()
		return nil, artifactPathError(err)
	}
	if !info.Mode().IsRegular() {
		file.Close()
		return nil, status.Error(codes.InvalidArgument, "artifact is not a regular file")
	}
	return file, nil
}

func artifactOpenError(parentFD int, name string, err error) error {
	// Linux returns ENOTDIR for a directory symlink opened with O_NOFOLLOW.
	var info unix.Stat_t
	if err == unix.ELOOP || (err == unix.ENOTDIR &&
		unix.Fstatat(parentFD, name, &info, unix.AT_SYMLINK_NOFOLLOW) == nil && info.Mode&unix.S_IFMT == unix.S_IFLNK) {
		return status.Error(codes.PermissionDenied, "artifact path must not contain symbolic links")
	}
	if err == unix.ENOTDIR {
		return status.Error(codes.InvalidArgument, "artifact path contains a non-directory component")
	}
	return artifactPathError(err)
}

func artifactPathError(err error) error {
	if os.IsNotExist(err) {
		return status.Error(codes.NotFound, "artifact not found")
	}
	if os.IsPermission(err) {
		return status.Error(codes.PermissionDenied, "artifact is not accessible")
	}
	return status.Errorf(codes.Internal, "failed to resolve artifact: %v", err)
}
